calacademy-research/antcat

app/decorators/reference_decorator.rb
app/models/reference.rb
features/catalog/catalog_search.feature
features/references/search_references.feature
features/step_definitions/autocomplete_steps.rb
lib/antcat_rake_utils.rb
lib/tasks/database_maintenance.rake
lib/tasks/import_sample_data.rake
spec/lib/formatters/advanced_search_html_formatter_spec.rb
spec/models/references/reference_key_spec.rb

Forgot to push this one. What we talked about earlier: 'external_link.png' --> "716237123".

Internal-External links

---

INSTALL.md
README.md

Was not parsed as headings on GitHub.

Update markdown syntax in READMEs

---

Gemfile.lock
app/views/taxa/form/_name_status_flags_section.haml
lib/database_scripts/scripts/missing_references_in_protonym_authorships.rb
lib/database_scripts/scripts/non_displayable_valid_taxa.rb
lib/database_scripts/scripts/orphaned_protonyms.rb
lib/database_scripts/scripts/possibly_duplicated_journal_names.rb
lib/database_scripts/scripts/taxa_with_non_matching_name_types.rb
lib/database_scripts/scripts/taxa_with_the_same_name_cache_value.rb
lib/database_scripts/scripts/taxa_with_the_same_name_object.rb
lib/database_scripts/scripts/valid_taxa_that_may_be_synonyms.rb

Fix non-displayable valid taxa

---

app/assets/javascripts/controllers/catalog/show/taxon_browser_tab.coffee

Fix for #185.
CI is green: https://travis-ci.org/jonkerz/antcat/builds/239172475?utm_source=github_status&utm_medium=notification

Fix AJAX loading of the 'ALL TAXA' tab

---

app/assets/stylesheets/site/_icons.sass

Fix issue with arrow icons in tables

---

app/helpers/compare_revisions_helper.rb
app/views/compare_revisions/_formatted.haml

Compare revisions: quickfix to show something when the item cannot be rendered

---

app/models/citation.rb
app/models/protonym.rb
lib/database_scripts/scripts/protonyms_with_references_missing_year.rb

Db script: protonyms with references missing year

---

lib/database_scripts/scripts/duplicated_reference_sections.rb
lib/database_scripts/scripts/duplicated_synonyms.rb
lib/dedupe_reference_sections.rb
lib/dedupe_synonyms.rb

New database scripts x 2: Duplicated synonyms /  Duplicated reference sections

---

app/controllers/beta_and_such_controller.rb
app/controllers/editors_panels/versions_controller.rb
app/views/beta_and_such/show_version.haml
app/views/editors_panels/index.haml
app/views/editors_panels/versions/index.haml
app/views/editors_panels/versions/show.haml
config/breadcrumbs/editors_panel.rb
config/routes.rb

Tech: move versions controller

---

app/controllers/references/history_controller.rb
app/helpers/compare_revisions_helper.rb
app/models/reference.rb
app/models/reference_formatter_cache.rb
app/models/taxa/taxa_references.rb
app/models/taxon.rb
app/views/activities/_table.haml
app/views/editors_panels/versions/index.haml
app/views/feed/activities/_reference.haml
app/views/feed/activities/_reference_section.haml
app/views/feed/activities/_taxon_history_item.haml
app/views/layouts/references.haml
app/views/references/history/_compare_revision_template.haml
app/views/references/history/index.haml
app/views/references/show.haml
app/views/shared/_not_part_of_the_catalog.haml
config/breadcrumbs/references.rb
config/routes.rb
features/changes/compare_revisions.feature

Add revision comparer to references

---

app/assets/javascripts/all_pages/show_hide_toggler.coffee
app/controllers/catalog/history_controller.rb
app/models/taxon.rb
app/views/catalog/_editor_buttons.haml
app/views/catalog/history/show.haml
app/views/compare_revisions/_difference_between_revisions.haml
app/views/compare_revisions/show.haml
app/views/feedback/show.haml
config/breadcrumbs/catalog.rb
config/routes.rb
features/changes/compare_revisions.feature

Add revision comparer to taxa

---

app/models/citation.rb
config/application.rb
lib/database_scripts/scripts/epi_and_questionmark_taxt_tags.rb

New database script: 'Catalog: Epi and questionmark taxt tags'

---

lib/database_scripts/renderers/markdown.rb
lib/database_scripts/scripts/broken_taxt_tags.rb
lib/tasks/database_maintenance.rake

Also includes this log:
```
Searching... (in 'development' database)
ReferenceSection --> references_taxt...
ReferenceSection --> title_taxt...
ReferenceSection --> subtitle_taxt...
TaxonHistoryItem --> taxt...
Taxon --> headline_notes_taxt...
Taxon --> type_taxt...
Taxon --> genus_species_header_notes_taxt...
Citation --> notes_taxt...
Found 4183 ref(s), 98 nam(s), and 9147 tax(s) (unique only).
----------
Searching for non-existing...
Found 3 ref(s), 43 nam(s), and 11 tax(s).
----------
Listing which...
ref: [133005, 132986, 133017]
nam: [139760, 139761, 141185, 142973, 142974, 142975, 142976, 137712, 142978, 142979, 142960, 143190, 143192, 170314, 151534, 151533, 169706, 169707, 135927, 154508, 154509, 154732, 134560, 136814, 157027, 169695, 169696, 169697, 169698, 136647, 165111, …
```

Database script: 'Catalog, references: Broken taxt tags'

---

app/models/taxa/tribe.rb
spec/models/taxa/tribe_spec.rb

Add species count summaries to tribal taxon pages

---

app/decorators/taxon_decorator/header.rb
lib/database_scripts/scripts/journals_by_reference_count.rb

Database script: 'References: Journals by reference count'

---

lib/database_scripts/scripts/duplicated_reference_sections.rb
lib/database_scripts/scripts/duplicated_synonyms.rb
lib/database_scripts/scripts/non_displayable_valid_taxa.rb
lib/database_scripts/scripts/protonyms_with_references_missing_year.rb
lib/database_scripts/scripts/subspecies_without_genus.rb
lib/database_scripts/scripts/valid_taxa_with_a_current_valid_taxon_id.rb

Db script: valid taxa with a current valid taxon

---

app/assets/javascripts/controllers/taxa/form/_bundle.coffee
app/assets/javascripts/controllers/taxa/form/locality_autocompletion.coffee
app/assets/javascripts/controllers/taxa/form/type_specimen_repository_autocompletion.coffee
app/assets/stylesheets/controllers/_taxa.sass
app/controllers/protonyms/localities_controller.rb
app/controllers/type_specimen_repositories_controller.rb
app/controllers/types/type_specimen_repositories_controller.rb
app/models/locality.rb
config/routes.rb
features/step_definitions/typeahead_autocomplete_steps.rb
features/step_definitions/types_steps.rb
features/support/wait_for_jquery.rb
features/taxon_form/autocompletion.feature

Autocomplete localities

---

app/assets/stylesheets/controllers/_references.sass
app/assets/stylesheets/site/reference_table.sass
app/controllers/authors_controller.rb
app/models/author.rb
app/models/reference.rb
app/views/authors/edit.haml
app/views/authors/index.haml
app/views/authors/show.haml
app/views/references/index.haml
app/views/references/show.haml
app/views/shared/_reference_table.haml
config/breadcrumbs/references.rb
config/routes.rb
features/references/browse.feature
features/references_related/authors.feature

Interlink authors and references

---

db/migrate/20170712192817_change_taxon_verbatim_type_locality_to_text.rb
db/schema.rb

Change taxon verbatim type locality to text

---

app/controllers/database_scripts_controller.rb
lib/database_scripts/renderers/markdown.rb
lib/database_scripts/scripts/bad_subfamily_names.rb
lib/database_scripts/scripts/broken_taxt_tags.rb
lib/database_scripts/scripts/duplicated_synonyms.rb
lib/database_scripts/scripts/epi_and_questionmark_taxt_tags.rb
lib/database_scripts/scripts/journals_by_reference_count.rb
lib/database_scripts/scripts/locality_but_no_biogeographic_region.rb
lib/database_scripts/scripts/missing_references_in_protonym_authorships.rb
lib/database_scripts/scripts/protonym_localities.rb
lib/database_scripts/scripts/protonyms_with_references_missing_year.rb
lib/database_scripts/scripts/redundant_curly_braces_in_taxt_items.rb
lib/database_scripts/scripts/self_referencing_synonym_records.rb
lib/database_scripts/scripts/synonym_records_referencing_non_existent_taxa.rb
lib/database_scripts/scripts/type_specimen_repositories.rb
lib/database_scripts/scripts/valid_taxa_with_a_current_valid_taxon_id.rb

Database scripts x 2 (synonym-related + tweaks)

---

config/routes.rb
spec/controllers/editors_panels_controller_spec.rb
spec/support/rspec.rb

Fix invite users route

---

app/database_scripts/database_scripts/number_of_species_described_by_author.rb

feat: Database script: 'Catalog: Number of species described by author'

---

app/assets/javascripts/application.js
app/assets/stylesheets/controllers/_authors.sass
app/assets/stylesheets/foundation_and_overrides.sass
app/controllers/authors_controller.rb
app/decorators/author_decorator.rb
app/helpers/application_helper.rb
app/models/author.rb
app/services/authors/described_taxa.rb
app/services/exporters/taxon_list/exporter.rb
app/views/authors/index.haml
app/views/authors/show.haml
config/breadcrumbs/references.rb
spec/decorators/author_decorator_spec.rb
spec/services/authors/described_taxa_spec.rb

Feat: Improve author pages

---

app/assets/stylesheets/foundation_and_overrides.sass
app/assets/stylesheets/site/_global.sass
app/decorators/reference_decorator.rb
app/helpers/application_helper.rb
app/models/reference.rb
app/views/authors/show.haml
app/views/journals/show.haml
app/views/references/show.haml

Feat: improve reference details page

---

app/database_scripts/database_scripts/non_displayable_obsolete_combinations.rb

Db script: 'Catalog: Non displayable obsolete combinations'

---

app/controllers/changes/undos_controller.rb
app/controllers/changes_controller.rb
app/controllers/default_references_controller.rb
app/controllers/references/reviews_controller.rb
app/helpers/changes_helper.rb
app/views/changes/undos/show.haml
config/routes.rb
spec/controllers/changes/undos_controller_spec.rb
spec/controllers/changes_controller_spec.rb

Redirect to previous page

---

app/models/reference.rb
app/models/references/reference_search.rb
db/migrate/20170909165610_remove_possess_and_cite_code_from_references.rb
db/schema.rb
public/swagger.yaml

feat: Remove possess and cite_code from references

---

app/views/catalog/_original_combination.haml

feat: Add author citations to "see references"

---

app/database_scripts/database_scripts/unavailable_taxa_with_a_current_valid_taxon.rb

Db script: 'Unavailable taxa with a current valid taxon'

---

app/database_scripts/database_scripts/unresolved_homonyms.rb

Db script: 'Unresolved homonyms'

---

app/database_scripts/database_scripts/unavailable_uncategorized_taxa_with_same_names_at_other_taxa.rb

Db script: 'Catalog: Unavailable uncategorized taxa with same names...'

---

app/views/catalog/_original_combination.haml

See: https://github.com/calacademy-research/antcat/pull/251#issuecomment-328661151

fix: Fix duplicated citation (AntCat 2.4.7)

---

app/decorators/taxon_decorator/headline.rb
app/decorators/taxon_decorator/headline_protonym.rb
app/decorators/taxon_decorator/headline_type.rb
spec/decorators/taxon_decorator/headline_protonym_spec.rb
spec/decorators/taxon_decorator/headline_spec.rb
spec/decorators/taxon_decorator/headline_type_spec.rb

Slightly better encapsulation.

Tech: split taxon decorator headline

---

app/database_scripts/database_scripts/valid_species_list.rb

Db script: valid taxon list (CSV)

---

app/decorators/activity_decorator.rb
app/models/activity.rb
app/models/author.rb
app/models/change.rb
app/models/concerns/taxa/reorder_history_items.rb
app/models/concerns/trackable.rb
app/models/reference.rb
app/models/taxa/species_group/species.rb
app/models/taxa/species_group/subspecies.rb
app/views/activities/templates/actions/_execute_script.haml
db/migrate/20170919191827_add_edit_summary_to_activities.rb
db/schema.rb
features/feed/execute_script_activities.feature
features/step_definitions/feed_steps.rb

Feat: 'execute script' activity

---

app/controllers/database_scripts_controller.rb
app/database_scripts/database_scripts/bad_subfamily_names.rb
app/database_scripts/database_scripts/duplicated_synonyms.rb
app/database_scripts/database_scripts/orphaned_protonyms.rb
app/database_scripts/database_scripts/protonyms_with_references_missing_year.rb
app/database_scripts/database_scripts/unavailable_taxa_with_a_current_valid_taxon.rb
app/database_scripts/database_scripts/unavailable_uncategorized_taxa_with_same_names_at_other_taxa.rb
app/database_scripts/database_scripts/valid_taxa_with_a_current_valid_taxon_id.rb
app/database_scripts/database_scripts/valid_taxa_with_non_valid_parents.rb
app/models/database_script.rb
app/views/database_scripts/index.haml

Because the index is crowded as is.

Feat: show regression db scripts last in the list

---

app/database_scripts/database_scripts/junior_synonyms_listed_as_another_taxons_senior.rb
app/database_scripts/database_scripts/taxa_with_both_junior_and_senior_synonyms.rb
app/database_scripts/database_scripts/valid_taxa_listed_as_another_taxons_junior_synonym.rb

Related issue: #279
---
---
---

Add synonyms-related script(s) x 3

---

app/assets/stylesheets/controllers/_catalog.sass
app/assets/stylesheets/site/_global.sass
app/decorators/taxon_decorator/child_list.rb
app/models/concerns/taxa/synonyms.rb
app/views/catalog/_reference_sections.haml
app/views/catalog/_taxon_description.haml
spec/models/concerns/taxa/synonyms_spec.rb

List synonyms on catalog pages

---

app/assets/javascripts/widgets/reference_popup.coffee
app/assets/javascripts/widgets/taxt_editor.coffee
app/services/references/search/fulltext.rb

Issue: #291 
This PR:
- Attempt to prefill reference popup search box with selected text
- Order reference fulltext search results by Solr score

Feat: improve reference insertion

---

app/assets/javascripts/widgets/reference_popup.coffee
app/assets/javascripts/widgets/taxt_editor.coffee

… popup search box with selected text"
This reverts commit 53bf61e14c172323b12a03688c747f917c08dce6.
Introduced a bug when inserting a second reference.

AntCat 2.4.12: Revert "feat: Attempt to prefill reference"

---

app/database_scripts/database_scripts/incomplete_synonyms.rb
app/decorators/table_ref_decorator.rb
app/models/synonym.rb
spec/models/synonym_spec.rb

Feat: validate synonyms and db script

---

app/assets/stylesheets/controllers/_taxa.sass
app/controllers/changes/undos_controller.rb
app/controllers/reference_sections_controller.rb
app/controllers/references_controller.rb
app/controllers/taxa_controller.rb
app/controllers/taxon_history_items_controller.rb
app/models/reference_section.rb
app/views/activities/_table.haml
app/views/changes/undos/show.haml
app/views/reference_sections/_edit.haml
app/views/references/_form.haml
app/views/taxa/form/_buttons_save_section.haml
app/views/taxon_history_items/_edit.haml
features/changes/undo.feature
features/feed/changes_activities.feature
features/feed/reference_activities.feature
features/feed/taxon_activities.feature
features/reference_sections/edit_references_section.feature
features/step_definitions/feed_steps.rb
features/taxon_history_items/edit_history_item.feature

Feat: Edit summaries

---

app/database_scripts/database_scripts/synonyms_without_a_current_valid_taxon.rb

feat: Db script - 'Synonyms without a current valid taxon'

---

app/database_scripts/database_scripts/taxa_referencing_non_existing_taxa.rb

feat: Db script - 'Catalog: Taxa referencing non existing taxa'

---

app/database_scripts/database_scripts/taxa_with_more_than_one_senior_synonym.rb
app/views/activities/templates/actions/_execute_script.haml
lib/generators/templates/database_script.rb.erb

AntCat 2.4.16: Db script - taxa with more than one senior synonym

---

Gemfile
Gemfile.lock
config/environments/production.rb
config/newrelic.yml

Tech: Enable New Relic

---

app/assets/javascripts/controllers/taxa/not_really_form/synonyms_section.coffee
app/assets/javascripts/taxon_select.coffee
app/assets/stylesheets/controllers/_taxa.sass
app/controllers/synonyms_controller.rb
app/models/concerns/taxa/synonyms.rb
app/views/taxa/not_really_form/_synonym_form.haml
app/views/taxa/not_really_form/_synonyms_section.haml
features/step_definitions/edit_steps/synonym_section_steps.rb

Use new taxon selector for synonyms

---

.travis.yml
Gemfile
Gemfile.lock

AntCat 2.5.2: Upgrade to Ruby 2.3.3

---

app/decorators/taxon_decorator.rb
app/decorators/taxon_decorator/taxon_status.rb
app/views/catalog/_original_combination.haml
spec/decorators/taxon_decorator/taxon_status_spec.rb

Show author citations

---

app/database_scripts/database_scripts/species_and_subspecies_with_synonyms_not_in_the_same_genus.rb
features/feed/synonym_activities.feature

Db script: Synonyms and subspecies not in same genus as taxon

---

app/assets/javascripts/all_pages/global.coffee
app/assets/javascripts/application.js
app/assets/stylesheets/site/_global.sass
app/views/catalog/_type_fields.haml
vendor/assets/javascripts/jquery.truncate.js

Closes: #381 
Issue was that the text truncation did not take into account HTML elements.

fix: Show more show less not working

---

app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
app/controllers/changes_controller.rb
app/controllers/comments_controller.rb
app/controllers/default_references_controller.rb
app/controllers/references/reviews_controller.rb
app/controllers/site_notices_controller.rb
app/controllers/widget_tests_controller.rb
app/models/journal.rb
app/models/reference.rb
config/routes.rb
lib/revision_comparer.rb
spec/controllers/application_controller_spec.rb
spec/services/wikipedia/reference_exporter_spec.rb

Fix: deprecation warnings

---

app/database_scripts/database_scripts/fossil_taxa_with_biogeographic_regions.rb
app/database_scripts/database_scripts/pass_through_names_with_synonyms.rb
app/database_scripts/database_scripts/pass_through_names_with_taxts.rb
app/models/database_scripts/rendering.rb

Db scripts: pass through names and more

---

app/controllers/activities_controller.rb
app/models/activity.rb
app/views/activities/index.haml
features/feed/filtering.feature
features/step_definitions/feed_steps.rb

Less clutter in the activity feed.

feat: Hide automated edits by default

---

app/assets/javascripts/all_pages/global.coffee
app/assets/javascripts/markdown_and_friends/textarea_has_linkables.coffee
app/views/catalog/_type_fields.haml
app/views/taxa/not_really_form/_junior_and_senior_synonyms_section.haml

Tech: 2.6.3 tweaks

---

app/assets/javascripts/markdown_and_friends/textarea_has_linkables.coffee
app/services/autocomplete/autocomplete_taxa.rb
app/views/taxa/not_really_form/_junior_and_senior_synonyms_section.haml

Tweak taxon name autocompletion

---

app/assets/javascripts/markdown_and_friends/textarea_has_linkables.coffee
app/controllers/references_controller.rb
app/models/reference.rb
app/services/autocomplete/autocomplete_linkable_references.rb
app/views/references/_form.haml
app/views/references/show.haml
db/migrate/20180726194833_add_bolton_key_to_references.rb
db/schema.rb
features/reference_form/add_reference_successfully.feature
spec/controllers/references/search_controller_spec.rb
spec/controllers/references_controller_spec.rb
spec/services/autocomplete/autocomplete_linkable_references_spec.rb
spec/services/references/save_from_form_spec.rb

Improve reference autocomplete suggestions

---

app/assets/javascripts/markdown_and_friends/textarea_has_linkables.coffee
app/controllers/references_controller.rb
app/helpers/reference_helper.rb
app/models/reference.rb
app/services/autocomplete/autocomplete_linkable_references.rb
app/views/references/_form.haml
app/views/references/latest_additions/index.haml
app/views/references/show.haml
app/views/shared/_flash_messages.haml
db/migrate/20180726194833_add_bolton_key_to_references.rb
db/schema.rb
features/reference_form/add_reference_successfully.feature
spec/controllers/references/search_controller_spec.rb
spec/controllers/references_controller_spec.rb
spec/services/autocomplete/autocomplete_linkable_references_spec.rb
spec/services/references/save_from_form_spec.rb

AntCat 2.6.7

---

app/assets/javascripts/markdown_and_friends/textarea_has_linkables.coffee
app/models/reference.rb
app/services/autocomplete/autocomplete_linkable_references.rb
spec/services/autocomplete/autocomplete_linkable_references_spec.rb

Issue: See 4a01f15c79dd90444f3ed0e16ac07c8d5fdd8140.
Solution: Order by author and citation year, and show more suggestions.

Improve reference autocompletion no. 2

---

.rubocop.yml
Guardfile
app/controllers/catalog/search_controller.rb
app/helpers/advanced_searches_helper.rb
app/models/taxon.rb
app/services/taxa/advanced_search.rb
app/views/catalog/search/_advanced_search_form.haml
features/tooltips/edit_tooltips.feature
spec/factories/taxa.rb
spec/services/taxa/advanced_search_spec.rb

More taxon search options

---

app/database_scripts/database_scripts/non_explicit_incertae_sedis_taxa.rb
app/decorators/taxon_decorator/child_list.rb
app/models/database_scripts/renderers/as_table.rb
spec/decorators/taxon_decorator/child_list_spec.rb
spec/models/database_scripts/renderers/as_table_spec.rb

Fix: genera incertae in Formicidae labels

---

app/assets/javascripts/controllers/taxa/move_items/select_checkboxes.coffee
app/controllers/taxa/move_items_controller.rb
app/decorators/taxon_decorator.rb
app/models/activity.rb
app/services/taxa/move_items.rb
app/views/activities/templates/actions/_move_items.haml
app/views/catalog/_editor_buttons.haml
app/views/catalog/search/index.haml
app/views/taxa/move_items/new.haml
app/views/taxa/move_items/show.haml
config/breadcrumbs/taxa.rb
config/routes.rb
features/move_items/move.feature
features/step_definitions/edit_steps/edit_steps.rb
spec/controllers/taxa/move_items_controller_spec.rb
spec/decorators/taxon_decorator_spec.rb
spec/services/taxa/move_items_spec.rb

Move history items

---

app/models/reference_document.rb
features/reference_form/edit_reference_unsuccessfully.feature
features/step_definitions/reference_steps.rb
spec/models/reference_document_spec.rb
spec/models/references/reference_has_document_spec.rb

Don't validate reference URL existence

---

app/controllers/taxa/create_obsolete_combinations_controller.rb
app/models/activity.rb
app/services/taxa/create_obsolete_combination.rb
app/views/activities/templates/actions/_create_obsolete_combination.haml
app/views/catalog/_editor_buttons.haml
app/views/taxa/create_obsolete_combinations/show.haml
config/breadcrumbs/taxa.rb
config/routes.rb
features/step_definitions/edit_steps/edit_steps.rb
features/taxon_operations/create_obsolete_combination.feature
spec/controllers/taxa/create_obsolete_combinations_controller_spec.rb
spec/services/taxa/create_obsolete_combination_spec.rb

Create missing obsolete combination button

---

app/controllers/taxa/force_parent_changes_controller.rb
app/models/taxa/genus_group/genus.rb
app/views/taxa/force_parent_changes/show.haml
app/views/taxa/form/_main_form.haml
spec/models/taxa/genus_group/genus_spec.rb

Per #496.
Was removed in 21bef7594a00cdf9abb2fee1310fe25552131024 because I did not know what it did.

Incertae sedis and excluded

---

.travis.yml
Gemfile
app/assets/javascripts/application.js
app/assets/javascripts/logged_in_only.js
app/controllers/catalog_controller.rb
app/controllers/feedback_controller.rb
app/decorators/taxon_decorator/child_list.rb
app/helpers/application_helper.rb
app/services/markdowns/parse_antcat_hooks.rb
app/services/taxa/statistics.rb
app/services/taxon_browser/tab.rb
app/views/catalog/_taxon_description.haml
config/environments/production.rb
spec/decorators/taxon_decorator/child_list_spec.rb
spec/helpers/application_helper_spec.rb
spec/lib/taxt_presenter_spec.rb
spec/services/markdowns/parse_antcat_hooks_spec.rb
spec/services/markdowns/render_spec.rb

Let's throw in some performance tweaks.
Solves:
- Good start of the new year
- Brings good luck

Improve performance 2019 edition

---

app/controllers/markdown_controller.rb
app/decorators/reference_decorator.rb
app/decorators/reference_decorator/article_reference_decorator.rb
app/decorators/reference_decorator/book_reference_decorator.rb
app/decorators/reference_decorator/missing_reference_decorator.rb
app/decorators/reference_decorator/nested_reference_decorator.rb
app/decorators/reference_decorator/unknown_reference_decorator.rb
app/helpers/tooltip_helper.rb
app/models/database_scripts/renderers/markdown.rb
app/models/reference.rb
app/services/markdowns/render.rb
app/services/types/format_type_field.rb
app/views/activities/templates/_reference.haml
app/views/comments/_comments_table.haml
config/breadcrumbs/references.rb
lib/taxt_presenter.rb
spec/decorators/reference_decorator/article_reference_decorator_spec.rb
spec/decorators/reference_decorator/book_reference_decorator_spec.rb
spec/decorators/reference_decorator/missing_reference_decorator_spec.rb
spec/decorators/reference_decorator/nested_reference_decorator_spec.rb
spec/decorators/reference_decorator/unknown_reference_decorator_spec.rb
spec/decorators/reference_decorator_spec.rb
spec/helpers/tooltip_helper_spec.rb
spec/lib/taxt_presenter_spec.rb
spec/models/reference_spec.rb

A must-have if we are to allow anyone to sing up (which we want!).

Fix XSS issues

---

app/database_scripts/database_scripts/inconsistent_synonyms.rb

New db script - 'Synonyms: Inconsistent synonyms'

---

app/database_scripts/database_scripts/non_standard_reference_sections.rb

New db script 'Catalog: Non-standard reference sections'

---

app/database_scripts/database_scripts/same_named_passthrough_names.rb

New db script - 'Catalog: Same named passthrough names'

---

app/assets/stylesheets/site/_navigation.sass
app/controllers/catalog_controller.rb
app/controllers/name_fields_controller.rb
app/database_scripts/database_scripts/inconsistent_synonyms.rb
app/database_scripts/database_scripts/non_standard_reference_sections.rb
app/database_scripts/database_scripts/same_named_passthrough_names.rb
app/database_scripts/database_scripts/valid_species_list.rb
app/decorators/activity_decorator.rb
app/models/issue.rb
app/models/journal.rb
app/models/name.rb
app/models/site_notice.rb
app/views/application/_navigation.haml
app/views/feedback/show.haml
app/views/issues/show.haml
app/views/site_notices/show.haml
app/views/taxa/_form/_type_section.haml
features/editors_panel/site_notices.feature
features/step_definitions/site_notice_steps.rb
features/step_definitions/user_steps.rb

AntCat 3.0.1

---

app/assets/javascripts/logged_in_only.js
app/assets/javascripts/logged_in_only/add_to_recently_used_references.coffee
app/views/references/_reference.haml
app/views/references/show.haml
features/markdown/autocompletion.feature
features/step_definitions/reference_steps.rb
features/support/paths.rb
spec/controllers/my/recently_used_references_controller_spec.rb
vendor/assets/javascripts/notify.js

For the `+Reference` button (or `!!` shorthand).

Add to recently used references

---

.rubocop.yml
app/assets/javascripts/controllers/protonyms/form.coffee
app/assets/javascripts/controllers/taxa/form/locality_autocompletion.coffee
app/assets/javascripts/markdown_and_friends/preview_markdown.coffee
app/assets/javascripts/protonym_select.coffee
app/controllers/protonyms_controller.rb
app/controllers/taxa_controller.rb
app/forms/taxon_form.rb
app/helpers/protonym_select_helper.rb
app/services/autocomplete/autocomplete_protonyms.rb
app/views/activities/templates/_protonym.haml
app/views/protonyms/_form.haml
app/views/protonyms/edit.haml
app/views/protonyms/show.haml
app/views/taxa/_form.haml
app/views/taxa/_form/_protonym_section.haml
config/breadcrumbs/catalog.rb
config/routes.rb
features/feed/protonym_activities.feature
features/protonyms/manage.feature
features/step_definitions/protonym_steps.rb
features/step_definitions/taxon_steps/genus_steps.rb
features/support/paths.rb
features/taxon_form/autocompletion.feature
features/taxon_form/edit_taxon.feature
features/taxon_form/edit_taxon_names.feature
spec/controllers/protonyms_controller_spec.rb
spec/controllers/taxa_controller_spec.rb

For #570
* Edit protonyms
* Change protonym for existing taxa
* Select protonym for new taxa

Manage protonyms

---

app/assets/javascripts/markdown_and_friends/preview_markdown.coffee
app/controllers/editors_panels/bolton_keys_to_ref_tags_controller.rb
features/markdown/preview.feature
features/step_definitions/taxon_history_item_steps.rb

Inline 'Convert Bolton keys' button

---

app/assets/javascripts/markdown_and_friends/textarea_has_linkables.coffee
app/database_scripts/database_scripts/possibly_duplicated_journal_names.rb
app/services/autocomplete/autocomplete_linkable_journals.rb
app/services/markdowns/parse_antcat_hooks.rb
app/views/markdown/_formatting_help.haml
features/markdown/autocompletion.feature
features/markdown/preview.feature
features/step_definitions/markdown_steps.rb
spec/services/markdowns/render_spec.rb

Not used a lot. Less code to maintain.

Remove journal markdown links

---

app/database_scripts/database_scripts/taxt_items_with_hardcoded_names.rb

Db script for finding hardcoded nams (previously nam tags)

---

app/assets/javascripts/all_pages/global.coffee
app/models/reference.rb
app/services/references/search/extract_keywords.rb
app/services/references/search/fulltext.rb
app/services/references/search/fulltext_light.rb
app/views/references/search/help.haml
app/views/references/search/index.haml
solr/conf/schema.xml
spec/services/references/search/extract_keywords_spec.rb
spec/services/references/search/fulltext_light_spec.rb
spec/services/references/search/fulltext_spec.rb

Slight tweak for #423
Closes #513

DOI keyword search

---

app/views/application/_footer.haml
app/views/pages/about.html.haml

Fix Broken Swagger link

---

app/controllers/names/history_controller.rb
app/controllers/names_controller.rb
app/helpers/tooltip_helper.rb
app/models/name.rb
app/models/names/species_group/subspecies_name.rb
app/services/revision_history_path.rb
app/views/activities/templates/_name.haml
app/views/names/_form.haml
app/views/names/edit.haml
app/views/names/history/index.haml
app/views/names/show.haml
app/views/protonyms/show.haml
app/views/taxa/_form/_main_form.haml
config/breadcrumbs/catalog.rb
config/routes.rb
spec/controllers/names_controller_spec.rb
spec/decorators/taxon_decorator/link_each_epithet_spec.rb
spec/models/name_spec.rb
spec/models/names/species_group/subspecies_name_spec.rb

Show and edit name records

---

app/controllers/taxa/convert_to_subspecies_controller.rb
app/controllers/taxa/elevate_to_species_controller.rb
app/decorators/protonym_decorator.rb
app/decorators/taxon_decorator/link_each_epithet.rb
app/helpers/taxon_select_helper.rb
app/models/concerns/taxa/callbacks_and_validations.rb
app/models/name.rb
app/models/names/genus_group_name.rb
app/models/names/species_group_name.rb
app/models/taxa/species_group_taxon.rb
app/models/taxon.rb
app/services/names/create_name_from_string.rb
app/services/taxa/convert_to_subspecies.rb
app/services/taxa/create_obsolete_combination.rb
app/services/taxa/elevate_to_species.rb
app/views/names/show.haml
app/views/taxa/create_obsolete_combinations/show.haml
config/breadcrumbs/catalog.rb
db/migrate/20190406233131_remove_name_html_and_epithet_html_from_names.rb
db/schema.rb
spec/decorators/table_ref_decorator_spec.rb
spec/factories/names.rb
spec/models/name_spec.rb
spec/models/taxa/species_group/subspecies_spec.rb
spec/services/names/create_name_from_string_spec.rb
spec/services/taxa/create_obsolete_combination_spec.rb

Dynamic HTML names - part 2

---

app/controllers/names_controller.rb
app/database_scripts/database_scripts/family_or_subfamily_names.rb
app/database_scripts/database_scripts/higher_rank_names_containing_spaces.rb
app/models/name.rb
app/models/names/species_group/subspecies_name.rb
app/models/names/species_group_name.rb
app/views/names/_form.haml
app/views/names/show.haml
config/routes.rb
spec/controllers/names_controller_spec.rb
spec/models/name_spec.rb
spec/models/names/species_group/species_name_spec.rb
spec/models/names/species_group/subspecies_name_spec.rb

Delete name button and more validations

---

db/migrate/20190413032640_add_user_foreign_keys.rb
db/migrate/20190413035117_add_taxon_foreign_keys.rb
db/schema.rb

Taxon and user foreign keys

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
app/assets/javascripts/rails-ujs-confirm-with-edit-summary.coffee

Upgrade to Ruby 2.4.5 (AntCat 3.0.20)

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock

This reverts commit 8de68aafb15429d26c9c70b3d0f0799a6bd51a64.

Revert "feat: Upgrade to ruby 2.4.5"

---

app/assets/javascripts/check_name_conflicts.coffee
app/assets/stylesheets/widgets/_check_name_conflicts.sass
app/controllers/names/check_name_conflicts_controller.rb
app/database_scripts/database_scripts/family_or_subfamily_names.rb
app/database_scripts/database_scripts/orphaned_protonyms.rb
app/decorators/application_decorator.rb
app/decorators/change_decorator.rb
app/decorators/reference_decorator.rb
app/decorators/taxon_decorator.rb
app/models/name.rb
app/services/names/find_conflicts.rb
app/views/editors_panels/index.haml
app/views/names/_form.haml
config/routes.rb
features/names/manage.feature
features/step_definitions/protonym_steps.rb
spec/controllers/names/check_name_conflicts_controller_spec.rb

AntCat 3.0.22

---

app/database_scripts/database_scripts/protonyms_to_be_deduped.rb
app/database_scripts/database_scripts/protonyms_with_same_authorship_record.rb
app/database_scripts/database_scripts/protonyms_with_same_name_and_reference.rb
app/database_scripts/database_scripts/protonyms_with_same_name_record.rb
app/database_scripts/database_scripts/taxa_with_same_name_and_status.rb
app/database_scripts/database_scripts/taxa_with_the_same_name_cache_value.rb
app/database_scripts/database_scripts/taxa_with_the_same_name_object.rb
app/services/references/search/fulltext.rb
db/migrate/20190503152714_add_not_nulls_and_column_defaults_to_protonyms.rb
db/schema.rb
features/changes/compare_revisions.feature

AntCat 3.0.23

---

app/controllers/editors_panels_controller.rb
app/controllers/issues_controller.rb
app/controllers/protonyms_controller.rb
app/database_scripts/database_scripts/obsolete_combinations_with_same_name_as_protonym.rb
app/database_scripts/database_scripts/protonyms_to_be_deduped.rb
app/database_scripts/database_scripts/protonyms_with_more_than_one_valid_taxon.rb
app/decorators/protonym_decorator.rb
app/models/reference_section.rb
app/services/exporters/antweb/export_headline_protonym.rb
app/views/catalog/_editor_buttons.haml
app/views/catalog/_taxon_description.haml
app/views/protonyms/history/_compare_revision_template.haml
app/views/protonyms/index.haml
app/views/protonyms/new.haml
config/breadcrumbs/catalog.rb
config/routes.rb
db/migrate/20190504225010_add_not_nulls_and_defaults_to_taxa_columns.rb
db/schema.rb
features/changes/compare_revisions.feature
features/step_definitions/edit_steps/edit_steps.rb
features/taxon_form/edit_taxon.feature
features/widgets/taxon_selector.feature
lib/dev_monkey_patches/ant_cat.rb
spec/controllers/protonyms_controller_spec.rb

AntCat 3.0.25

---

app/decorators/taxon_decorator/taxon_status.rb
app/models/concerns/taxa/callbacks_and_validations.rb
app/models/concerns/trackable.rb
app/presenters/advanced_search_presenter.rb
script/load.sh
script/reset_database.sh

AntCat 3.0.26

---

app/assets/javascripts/markdown_and_friends/preview_markdown.coffee
app/assets/javascripts/taxt_editor.coffee
features/markdown/preview.feature

Tweak editing of history items (AntCat 3.0.30)

---

app/controllers/catalog/fix_random_controller.rb
app/database_scripts/database_scripts/extant_taxa_in_fossil_genera.rb
app/database_scripts/database_scripts/protonyms_with_more_than_one_valid_taxon.rb
app/database_scripts/database_scripts/protonyms_with_same_authorship_record.rb
app/services/exporters/antweb/antweb_attributes.rb
app/services/exporters/antweb/export_taxon.rb
app/services/exporters/antweb/exporter.rb
app/views/layouts/application.haml
config/breadcrumbs/editors_panel.rb
spec/services/exporters/antweb/export_taxon_spec.rb

Tweaks and updated scripts (AntCat 3.0.31)

---

db/migrate/20190713041336_move_type_fields_to_protonym.rb
db/migrate/20190713041339_move_biogeographic_region_to_protonyms.rb
db/migrate/20190713041345_remove_type_information_columns_from_taxa.rb
db/migrate/20190713041346_remove_biogeographic_region_from_taxa.rb
db/schema.rb

Remove moved type information columns

---

app/decorators/taxon_decorator.rb
app/models/name.rb
app/models/taxa/subtribe.rb
app/models/taxa/tribe.rb
app/models/taxon_browser/browser.rb
app/models/taxon_browser/links_to_extra_tabs.rb
app/models/taxon_browser/tab.rb
app/models/taxon_browser/tabs/extra_tab.rb
app/models/taxon_browser/tabs/taxon_tab.rb
app/services/taxa/search/advanced_search.rb
config/breadcrumbs/catalog.rb
spec/factories/names.rb
spec/factories/taxa.rb
spec/models/taxa/subtribe_spec.rb
spec/models/taxon_browser/links_to_extra_tabs_spec.rb

Add `Subtribe` class and make subtribes browsable

---

app/controllers/catalog/searches_controller.rb
app/presenters/advanced_search_presenter.rb
app/presenters/advanced_search_presenter/html.rb
app/services/taxa/search/advanced_search.rb
app/views/catalog/searches/_advanced_search_form.haml
app/views/catalog/searches/_results.haml
spec/services/taxa/search/advanced_search_spec.rb

Search by protonym in advanced search form

---

app/assets/stylesheets/site/_global.sass
app/controllers/taxa_controller.rb
app/database_scripts/database_scripts/obsolete_combinations_with_same_name_as_protonym.rb
app/database_scripts/database_scripts/protonyms_with_more_than_one_original_combination.rb
app/models/status.rb
app/models/taxon.rb
app/presenters/advanced_search_presenter.rb
app/services/exporters/antweb/export_taxon.rb
app/services/taxa/statistics/fetch_statistics.rb
app/views/catalog/show.haml
app/views/protonyms/_form.haml
app/views/protonyms/show.haml
app/views/taxa/_form/_main_form.haml
app/views/taxon_browser/_container.haml
db/migrate/20190802161827_add_original_combination_to_taxa.rb
db/schema.rb
spec/controllers/taxa_controller_spec.rb
spec/factories/taxa.rb
spec/services/exporters/antweb/export_taxon_spec.rb
spec/services/taxa/statistics/fetch_statistics_spec.rb

Add original combination as a parallel status

---

app/operations/operations/convert_to_obsolete_combination.rb
app/policies/create_combination_policy.rb
spec/operations/operations/convert_to_obsolete_combination_spec.rb
spec/operations/operations/create_new_combination_spec.rb
spec/policies/create_combination_policy_spec.rb

Obsolete combination conversions

---

app/database_scripts/database_scripts/auto_generated_taxa.rb
app/database_scripts/database_scripts/obsolete_combinations_with_obsolete_combinations.rb
app/database_scripts/database_scripts/orphaned_author_names.rb
app/database_scripts/database_scripts/orphaned_reference_documents.rb
app/database_scripts/database_scripts/quadrinomials.rb
app/database_scripts/database_scripts/references_with_blank_pdf_urls_and_filenames.rb
app/database_scripts/database_scripts/references_with_undownloadable_pdfs.rb
app/database_scripts/database_scripts/replacement_names_used_for_more_than_one_taxon.rb
app/database_scripts/database_scripts/subspecies_list_in_history_item.rb
app/database_scripts/database_scripts/type_taxa_assigned_to_more_than_one_taxon.rb
app/database_scripts/database_scripts/unavailable_uncategorized_taxa.rb
app/operations/operations/convert_to_obsolete_combination.rb
app/policies/create_combination_policy.rb
app/views/catalog/show.haml
spec/operations/operations/convert_to_obsolete_combination_spec.rb
spec/operations/operations/create_new_combination_spec.rb
spec/policies/create_combination_policy_spec.rb

AntCat 3.2.13

---

app/database_scripts/database_scripts/family_or_subfamily_names.rb
app/database_scripts/database_scripts/taxa_with_non_matching_name_types.rb
app/database_scripts/database_scripts/unparsable_names.rb
app/models/name.rb
app/models/names/species_group/subspecies_name.rb
app/services/exporters/antweb/antweb_attributes.rb
app/services/names/build_name_from_string.rb
app/services/taxa/child_list.rb
app/views/names/show.haml
app/views/taxa/create_obsolete_combinations/show.haml
db/migrate/20200108151027_remove_epithets_from_names.rb
db/schema.rb
public/api/v1/swagger.yaml
spec/controllers/names_controller_spec.rb
spec/models/name_spec.rb
spec/models/names/genus_group/subgenus_name_spec.rb
spec/models/names/species_group/species_name_spec.rb
spec/models/names/species_group/subspecies_name_spec.rb
spec/models/taxa/species_group/subspecies_spec.rb
spec/services/names/build_name_from_string_spec.rb
spec/services/taxa/operations/elevate_to_species_spec.rb

Meta issue: #774
db dump: `antcat.2020-01-08T10-15-03.sql.gz`

Remove `names.epithets` and tweaks

---

app/assets/stylesheets/site/_global.sass
app/database_scripts/database_scripts/history_items_without_ref_or_tax_tags.rb
app/database_scripts/database_scripts/taxa_listed_as_homonym_of_self_in_history_item.rb
app/models/protonym.rb
app/models/taxon.rb
app/models/taxon_history_item.rb
app/models/taxt.rb
app/policies/taxon_policy.rb
app/services/taxa/operations/create_obsolete_combination.rb
app/views/catalog/_show/_editor_buttons.haml
app/views/catalog/_show/_editors_sidebar.haml
app/views/catalog/_show/_taxon_description.haml
config/locales/en.yml
spec/factories/taxa.rb
spec/models/taxon_history_item_spec.rb
spec/models/taxon_spec.rb
spec/policies/taxon_policy_spec.rb
spec/services/taxa/operations/create_obsolete_combination_spec.rb

AntCat 3.3.1

---

app/database_scripts/database_scripts/history_items_with_ref_tags_as_author_citations.rb
app/database_scripts/database_scripts/missing_references.rb
app/database_scripts/database_scripts/obsolete_combinations_with_protonyms_not_matching_its_current_valid_taxons_protonym.rb
app/database_scripts/database_scripts/obsolete_combinations_with_very_different_epithets.rb
app/models/taxon.rb
app/views/catalog/_show/_editors_sidebar.haml

Db script tweaks (AntCat 3.3.2)

---

.rubocop.yml
app/controllers/taxa/create_combination_helps_controller.rb
app/models/taxa/family.rb
app/models/taxa/genus_group/genus.rb
app/models/taxa/genus_group/subgenus.rb
app/models/taxa/genus_group_taxon.rb
app/models/taxa/species_group/species.rb
app/models/taxa/species_group/subspecies.rb
app/models/taxa/species_group_taxon.rb
app/models/taxa/subfamily.rb
app/models/taxa/tribe.rb
app/policies/taxon_policy.rb
app/services/taxa/find_epithet_in_genus.rb
app/services/taxa/operations/convert_to_subspecies.rb
app/services/taxa/operations/elevate_to_species.rb
spec/controllers/taxa/force_parent_changes_controller_spec.rb
spec/models/taxa/family_spec.rb
spec/models/taxa/genus_group/genus_spec.rb
spec/models/taxa/genus_group/subgenus_spec.rb
spec/models/taxa/species_group/infrasubspecies_spec.rb
spec/models/taxa/species_group/subspecies_spec.rb
spec/models/taxa/species_group_taxon_spec.rb
spec/models/taxa/subtribe_spec.rb
spec/models/taxa/tribe_spec.rb
spec/policies/taxon_policy_spec.rb
spec/services/taxa/find_epithet_in_genus_spec.rb
spec/services/taxa/operations/convert_to_subspecies_spec.rb
spec/services/taxa/operations/elevate_to_species_spec.rb

To make future changes easier. More to come.

Tech change: Put Taxon subclasses on a diet

---

app/services/exporters/antweb/antweb_attributes.rb
spec/services/exporters/antweb/antweb_attributes_spec.rb
spec/services/exporters/antweb/export_taxon_spec.rb

Export subgenus to AntWeb

---

Gemfile
Gemfile.lock

Good for the upcoming Ruby version update.

Gems: update sass-rails and swagger_ui_engine

---

Gemfile
Gemfile.lock

Attempt to fix failed gem update in #894.

gems: source sassc to GitHub

---

Gemfile
Gemfile.lock

Revert failed sass updates

---

Gemfile
Gemfile.lock
app/models/reference.rb

See https://github.com/geekq/workflow#activerecord

gems: Upgrade to workflow-activerecord

---

app/models/name.rb
app/models/rank.rb
app/models/taxon.rb
app/views/taxa/_form/_main_form.haml
spec/models/name_spec.rb
spec/models/rank_spec.rb
spec/models/taxon_spec.rb

Meta issue: #774
I think this is for the better, with or without #767.

Decouple rank and name

---

README.md
app/controllers/references/replace_missing_controller.rb
app/decorators/feedback_decorator.rb
app/helpers/dev_helper.rb
app/models/reference_document.rb
app/services/exporters/antweb/antweb_detax.rb
app/services/exporters/antweb/antweb_inline_citation.rb
app/services/exporters/antweb/exporter.rb
app/views/feedback/_feedback_modal.haml
app/views/pages/about.html.haml
app/views/shared/_markdown_formatting_help.haml
config/environments/production.rb
config/initializers/grape_swagger_rails.rb
lib/dev_monkey_patches.rb
lib/dev_monkey_patches/ant_cat.rb
public/api/v1/swagger.yaml
public/maintenance.html
spec/controllers/catalog/toggle_displays_controller_spec.rb
spec/controllers/site_notices_controller_spec.rb
spec/services/exporters/antweb/antweb_inline_citation_spec.rb
spec/services/exporters/antweb/export_taxon_spec.rb
spec/services/exporters/antweb/exporter_spec.rb
spec/support/test_links_helpers.rb

Update links to use https

---

app/decorators/taxon_decorator.rb
app/views/application/_footer.haml
app/views/editors_panels/index.haml
app/views/pages/about.html.haml
config/environments/production.rb
config/locales/devise.en.yml
config/newrelic.yml
spec/decorators/taxon_decorator_spec.rb
spec/services/exporters/antweb/export_taxon_spec.rb

More HTTPS

---

app/views/devise/sessions/new.haml
config/application.rb
config/environments/development.rb
config/environments/production.rb
features/user/forgot_password.feature

Enable "Forgot password" feature

---

public/robots.txt

Allow search engine bots

---

app/assets/stylesheets/controllers/_users.sass
app/controllers/application_controller.rb
app/controllers/my/registrations_controller.rb
app/controllers/users_controller.rb
app/models/author.rb
app/models/user.rb
app/views/authors/show.haml
app/views/devise/registrations/edit.haml
app/views/users/_form.haml
app/views/users/index.haml
app/views/users/show.haml
db/migrate/20200409201201_add_author_id_to_users.rb
db/schema.rb

Interlink authors and editors

---

app/injectable_formatters/default_formatter.rb
app/models/name_sti_subclasses/species_group_name_sti_subclasses/subspecies_name.rb
app/models/virtual_history_items/subspecies_list.rb
spec/injectable_formatters/default_formatter_spec.rb
spec/models/name_sti_subclasses/species_group_name_sti_subclasses/subspecies_name_spec.rb
spec/models/virtual_history_items/subspecies_list_spec.rb
spec/services/exporters/antweb/history/history_items_spec.rb

Shorten names in subspecies lists

---

app/controllers/references_controller.rb
app/database_scripts/database_scripts/citation_years_with_extras.rb
app/helpers/reference_select_helper.rb
app/models/reference.rb
app/services/autocomplete/autocomplete_references.rb
app/services/autocomplete/format_linkable_references.rb
app/services/references/formatted/expanded.rb
app/services/references/formatted/plain_text.rb
app/services/references/new_from_copy.rb
app/services/references/search/fulltext_light.rb
app/views/references/_form.haml
app/views/references/show.haml
db/migrate/20200417175412_add_stated_year_to_references.rb
db/schema.rb
features/reference_form/copy_reference.feature
features/reference_form/new_nested_reference_button.feature
public/api/v1/swagger.yaml
spec/controllers/api/v1/references_controller_spec.rb
spec/controllers/references_controller_spec.rb
spec/models/reference_spec.rb
spec/services/references/new_from_copy_spec.rb

Split extras from citation year into stated year

---

app/assets/stylesheets/site/_global.sass
app/controllers/wiki_pages_controller.rb
app/models/activity.rb
app/presenters/editors_panel_presenter.rb
app/views/editors_panels/index.haml
app/views/notifications/index.haml
app/views/shared/_markdown_formatting_help.haml
app/views/wiki_pages/index.haml
features/wiki_pages/add_and_edit.feature

More focus on wiki pages, and hide less relevant links.

Overhaul Editor's Panel sections

---

app/database_scripts/database_scripts/genus_gender_endings.rb
app/services/markdowns/parse_catalog_tags.rb

Issue was introduced in 90d258c4b52d805577bbf88a9bbed58c7f0f5fee.

Fix markdown and genus gender endings

---

app/assets/javascripts/all_pages/catalog_autocompletion.coffee
app/assets/javascripts/all_pages/reference_autocompletion.coffee
app/assets/stylesheets/site/_typeahead_autocompletion.sass
app/controllers/authors/autocompletes_controller.rb
app/controllers/catalog/autocompletes_controller.rb
app/controllers/journals/autocompletes_controller.rb
app/controllers/protonyms/autocompletes_controller.rb
app/controllers/references/autocompletes_controller.rb
app/queries/autocomplete/protonyms_query.rb
app/queries/autocomplete/taxa_query.rb
app/serializers/autocomplete/references_serializer.rb
spec/controllers/catalog/autocompletes_controller_spec.rb
spec/controllers/protonyms/autocompletes_controller_spec.rb
spec/controllers/references/autocompletes_controller_spec.rb
spec/serializers/autocomplete/references_serializer_spec.rb

Closes #781.
Also more Disco mode.

Include protonym search results in header search box

---

app/controllers/protonyms_controller.rb
app/controllers/taxa_controller.rb
app/decorators/protonym_decorator.rb
app/views/protonyms/_form.haml
app/views/taxa/_form/_protonym_section.haml
db/migrate/20200501210906_add_uncertain_locality_to_protonyms.rb
db/schema.rb
spec/controllers/api/v1/protonyms_controller_spec.rb
spec/decorators/protonym_decorator_spec.rb
spec/factories/protonyms.rb

Add "Uncertain locality" to protonyms

---

app/controllers/protonyms/what_links_heres_controller.rb
app/controllers/protonyms_controller.rb
app/database_scripts/database_scripts/orphaned_protonyms.rb
app/models/protonyms/what_links_here.rb
app/models/taxt.rb
app/views/protonyms/show.haml
app/views/protonyms/what_links_heres/show.haml
config/breadcrumbs/protonyms.rb
config/routes.rb
spec/controllers/protonyms/what_links_heres_controller_spec.rb
spec/controllers/protonyms_controller_spec.rb
spec/models/protonyms/what_links_here_spec.rb

And ensure protonyms with taxt tags cannot be deleted.

Add 'What Links Here' to protonyms

---

app/forms/reference_form.rb
features/reference_form/add_reference_successfully.feature
spec/controllers/references_controller_spec.rb
spec/forms/reference_form_spec.rb

Reference form: Strip unwanted characters from Bolton keys

---

app/controllers/application_controller.rb
app/controllers/feedbacks_controller.rb
app/controllers/my/registrations_controller.rb
app/helpers/recaptcha_helper.rb
app/services/verify_recaptcha_v3.rb
app/views/devise/registrations/new.haml
app/views/feedbacks/new.haml
config/settings/development.yml
config/settings/production.secret.yml.example
config/settings/test.yml

Use reCAPTCHA v3 for registration and feedback pages

---

.gitignore
config/database.yml.example
config/environments/staging.rb
config/settings/staging.secret.yml.example
config/settings/staging.yml
deploy/before_bundle.rb

Staging env config

---

app/assets/stylesheets/controllers/_catalog.sass
app/assets/stylesheets/site/_global.sass
app/controllers/api/v1/taxon_history_items_controller.rb
app/controllers/taxon_history_items_controller.rb
app/database_scripts/database_scripts/protonyms_with_rank_specific_and_unranked_history_items.rb
app/database_scripts/database_scripts/protonyms_with_rank_specific_history_items.rb
app/helpers/editor_helper.rb
app/models/rank.rb
app/models/taxon_history_item.rb
app/presenters/protonym_history_presenter.rb
app/views/catalog/_show/_taxon_description.haml
app/views/protonyms/show.haml
app/views/taxon_history_items/_form.haml
app/views/taxon_history_items/edit.haml
app/views/taxon_history_items/show.haml
db/migrate/20200526160135_add_rank_to_taxon_history_items.rb
db/schema.rb
spec/controllers/api/v1/taxon_history_items_controller_spec.rb
spec/controllers/taxon_history_items_controller_spec.rb
spec/models/taxon_history_item_spec.rb

Add rank to TaxonHistoryItem

---

app/decorators/paper_trail/version_decorator.rb
app/forms/protonym_form.rb
app/models/paper_trail/version.rb
app/views/editors_panels/versions/index.haml
app/views/editors_panels/versions/show.haml
features/protonyms/manage.feature
spec/models/paper_trail/version_spec.rb

And throw in activity links as a bonus.

Fix blanked attributes in protonym form

---

app/queries/references/fulltext_search_light_query.rb
app/queries/references/fulltext_search_query.rb
solr/conf/schema.xml
spec/queries/references/fulltext_search_query_spec.rb

Mixed-case and apostrophes reference search

---

app/controllers/quick_and_dirty_fixes_controller.rb
app/database_scripts/database_scripts/history_items_with_missing_tags.rb
app/models/database_scripts/render_helpers.rb
app/models/taxt.rb
app/services/quick_and_dirty_fixes/replace_missing_tags.rb
config/routes.rb

Quick-fix button for "Replace `missing` tag"

---

app/database_scripts/database_scripts/species_group_names_with_senior_synonyms_in_different_genus.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/10.

Db script 'Species-group names with senior synonyms in different genus'

---

app/assets/stylesheets/logged_in_only.sass
app/controllers/quick_and_dirty_fixes_controller.rb
app/database_scripts/database_scripts/history_items_with_missing_tags.rb
app/database_scripts/database_scripts/missing_taxa_to_be_created.rb
app/database_scripts/database_scripts/synonym_species_with_subspecies_with_incompatible_statuses.rb
app/database_scripts/database_scripts/taxac_tags_with_page_numbers.rb
app/services/markdowns/parse_catalog_tags.rb
app/services/quick_and_dirty_fixes/force_remove_pages_from_taxac_tags.rb
config/routes.rb
spec/services/markdowns/parse_catalog_tags_spec.rb

3.5.0 tweaks

---

db/migrate/20200617215602_move_forms_and_notes_taxt_to_protonyms.rb
db/migrate/20200624165712_remove_forms_and_notes_taxt_from_citations.rb
db/schema.rb

Remove `forms` and `notes_taxt` from `citations`

---

app/database_scripts/database_scripts/history_items_with_form_descriptions.rb
app/database_scripts/database_scripts/history_items_without_ref_or_tax_tags.rb
app/exporters/exporters/antweb/history/history_items.rb
app/injectable_formatters/antweb_formatter/detax.rb
app/models/taxon_history_item.rb
app/models/taxt.rb
app/operations/operations/move_history_items.rb
app/services/taxt/history_item_cleanup.rb
app/views/catalog/_show/_editors_sidebar.haml
app/views/catalog/_show/_taxon_description.haml
app/views/catalog/bolton/_taxon.haml
app/views/protonyms/show.haml
app/views/references/_form.haml
app/views/taxa/move_items/new.haml
app/views/taxa/move_items/show.haml
app/views/taxon_history_items/_form.haml
app/views/taxon_history_items/edit.haml
app/views/taxon_history_items/histories/_compare_revision_template.haml
app/views/taxon_history_items/index.haml
app/views/taxon_history_items/show.haml
features/step_definitions/reference_steps.rb
lib/tasks/db.rake
lib/tasks/rubycritic.rake
spec/injectable_formatters/antweb_formatter/detax_spec.rb

Prepare for hybrid history items

---

app/cleanup/protonym_history_presenter.rb
app/cleanup/quick_and_dirty_fixes/prefill_taxon_form.rb
app/controllers/catalog/bolton_controller.rb
app/database_scripts/database_scripts/hol_origin_taxa.rb
app/database_scripts/database_scripts/migration_origin_taxa.rb
app/database_scripts/database_scripts/non_valid_taxa_set_as_the_current_taxon_of_another_taxon.rb
app/database_scripts/database_scripts/obsolete_combinations_with_protonyms_not_matching_its_current_taxons_protonym.rb
app/database_scripts/database_scripts/obsolete_combinations_with_very_different_epithets.rb
app/database_scripts/database_scripts/pass_through_names_with_taxts.rb
app/database_scripts/database_scripts/reference_section_taxts.rb
app/database_scripts/database_scripts/valid_subspecies_in_invalid_species.rb
app/errors/taxa.rb
app/models/rank.rb
app/queries/autocomplete/references_query.rb
app/services/taxa/statistics/fetch_statistics.rb
app/services/taxa/statistics/format_statistics.rb
app/views/catalog/_show/_editor_buttons.haml
app/views/catalog/_show/logged_in_only/_editors_sidebar.haml
app/views/catalog/_show/logged_in_only/_history_items_via_protonym.haml
lib/service.rb
public/api/v1/swagger.yaml
spec/helpers/markdown_helper_spec.rb
spec/queries/catalog/advanced_search_query_spec.rb
spec/serializers/api/v1/taxon_serializer_spec.rb

3.5.3.1 tweaks

---

app/cleanup/quick_and_dirty_fixes/hardcoded_name_to_pro_tag.rb
app/controllers/quick_and_dirty_fixes_controller.rb
app/database_scripts/database_scripts/history_items_with_hardcoded_names_to_replace_with_pro_tags.rb
config/routes.rb

For #35
Closes https://github.com/calacademy-research/antcat-issues/issues/17

db-scripts: add HistoryItemsWithHardcodedNamesToReplaceWithProTags

---

app/cleanup/quick_and_dirty_fixes/prefill_taxon_form_for_quadrinomial.rb
app/database_scripts/database_scripts/quadrinomials_to_be_converted.rb

db-script: quick-add button for QuadrinomialsToBeConverted

---

app/database_scripts/database_scripts/protonyms_without_an_original_combination.rb
app/models/name.rb
app/services/names/clean_name.rb
app/services/names/identify_name_type.rb
db/migrate/20200708212345_add_cleaned_name_to_names.rb
db/schema.rb
spec/models/name_spec.rb
spec/services/names/clean_name_spec.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/31

Cleaned names

---

app/cleanup/quick_add/from_existing_protonym_factory.rb
app/cleanup/quick_add/from_existing_quadrinomial.rb
app/cleanup/quick_add/from_existing_species_protonym.rb
app/cleanup/quick_add/from_existing_subspecies_protonym.rb
app/cleanup/quick_add/from_hardcoded_name_factory.rb
app/cleanup/quick_add/from_hardcoded_subgenus_name.rb
app/cleanup/quick_add/quick_add_not_supported.rb
app/controllers/taxa_controller.rb
app/database_scripts/database_scripts/non_original_combinations_with_same_name_as_its_protonym.rb
app/database_scripts/database_scripts/points_to_replacement_name_and_uses_ref_tag_as_author_citation.rb
app/database_scripts/database_scripts/protonyms_without_a_taxon_with_same_cleaned_name_only_species.rb
app/database_scripts/database_scripts/protonyms_without_a_taxon_with_same_cleaned_name_only_subspecies.rb
app/database_scripts/database_scripts/protonyms_without_an_original_combination.rb
app/models/name.rb
app/models/soft_validations.rb

For https://github.com/calacademy-research/antcat-issues/issues/29

Quick-add missing combinations via protonyms

---

app/assets/javascripts/all_pages/global.coffee
app/assets/javascripts/markdown_and_friends/preview_markdown.coffee
app/assets/javascripts/taxt_editor.coffee
app/assets/stylesheets/site/_taxon_hover_preview.sass
app/controllers/catalog/autocompletes_controller.rb
app/controllers/protonyms/hover_previews_controller.rb
app/decorators/protonym_decorator.rb
app/injectable_formatters/catalog_formatter.rb
app/views/protonyms/hover_previews/_protonym.haml
config/routes.rb
spec/controllers/catalog/autocompletes_controller_spec.rb
spec/decorators/protonym_decorator_spec.rb
spec/injectable_formatters/catalog_formatter_spec.rb
spec/support/test_links_helpers.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/25

Protonym page previews on hover

---

app/decorators/protonym_decorator.rb
app/injectable_formatters/antweb_formatter.rb
app/injectable_formatters/antweb_formatter/detax.rb
app/models/taxt.rb
app/services/markdowns/parse_catalog_tags.rb
app/views/shared/_markdown_formatting_help.haml
spec/decorators/protonym_decorator_spec.rb
spec/injectable_formatters/antweb_formatter/detax_spec.rb
spec/injectable_formatters/antweb_formatter_spec.rb
spec/models/protonyms/what_links_here_spec.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/38

proac taxt tags

---

app/assets/stylesheets/controllers/_protonyms.sass
app/database_scripts/database_scripts/protonyms_with_nomen_attributes.rb
app/decorators/protonym_decorator.rb
app/forms/protonym_form.rb
app/models/name.rb
app/views/catalog/_show/logged_in_only/_editors_sidebar.haml
app/views/protonyms/_form.haml
app/views/protonyms/shared/_additional_data_for_editors.haml
app/views/protonyms/show.haml
app/views/taxa/_form/_protonym_section.haml
db/migrate/20200725140205_add_nomen_flags_to_protonyms.rb
db/schema.rb
spec/controllers/api/v1/protonyms_controller_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/44

Protonym nomen attributes

---

app/assets/stylesheets/site/_navigation.sass
app/helpers/application_helper.rb
app/presenters/editors/reference_presenter.rb
app/views/application/_breadcrumbs.haml
app/views/application/_navigation.haml
app/views/authors/index.haml
app/views/journals/index.haml
app/views/references/index.haml
app/views/references/latest_additions/index.haml
app/views/references/latest_changes/index.haml
app/views/references/search/index.haml
app/views/shared/references/_subnavigation.haml

Closes https://github.com/calacademy-research/antcat-issues/issues/48

Reference subnavigation

---

app/injectable_formatters/antweb_formatter/detax.rb
app/models/protonym.rb
app/models/taxt.rb
app/services/markdowns/parse_catalog_tags.rb
app/views/shared/_markdown_formatting_help.haml
spec/injectable_formatters/antweb_formatter/detax_spec.rb
spec/models/protonyms/what_links_here_spec.rb
spec/services/markdowns/parse_catalog_tags_spec.rb

Related:
* https://github.com/calacademy-research/antcat-issues/issues/8
* https://github.com/calacademy-research/antcat-issues/issues/16

New taxt tag: "prott" (protonym terminal taxon)

---

Gemfile
Gemfile.lock

With `sunspot_test` sourced to a fork, see https://github.com/collectiveidea/sunspot_test/pull/38

Upgrade to cucumber 4

---

app/forms/protonym_form.rb
app/models/protonym.rb
app/models/taxt.rb
app/views/protonyms/_form.haml
app/views/protonyms/shared/_additional_data_for_editors.haml
app/views/protonyms/show.haml
app/views/taxa/_form/_create_new_protonym_form.haml
app/views/taxa/_not_really_form/_protonym_section.haml
db/migrate/20201107000837_add_etymology_taxt_to_protonyms.rb
db/schema.rb
spec/controllers/protonyms_controller_spec.rb
spec/factories/protonyms.rb
spec/models/protonym_spec.rb
spec/models/protonyms/what_links_here_spec.rb
spec/models/references/what_links_here_spec.rb
spec/models/taxa/what_links_here_spec.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/69

Protonym etymology

---

app/controllers/catalog/autocompletes_controller.rb
app/controllers/protonyms/autocompletes_controller.rb
app/models/protonym.rb
app/models/taxon.rb
app/queries/autocomplete/protonyms_query.rb
app/queries/autocomplete/taxa_query.rb
features/markdown/autocompletion.feature
features/move_items/move.feature
features/taxon_form/edit_taxon.feature
features/taxon_operations/convert_to_subspecies.feature
features/taxon_operations/create_obsolete_combination.feature
features/taxon_operations/force_change_parent.feature
features/widgets/taxon_selector.feature
spec/controllers/catalog/autocompletes_controller_spec.rb
spec/controllers/protonyms/autocompletes_controller_spec.rb
spec/queries/autocomplete/protonyms_query_spec.rb
spec/queries/autocomplete/taxa_query_spec.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/72

Use Solr for autocompleting taxa and protonyms in dropdowns and in the taxt editor

---

app/assets/stylesheets/controllers/_references.sass
app/database_scripts/database_scripts/number_of_protonyms_by_author.rb
app/database_scripts/database_scripts/protonyms_with_etymology_taxt.rb
app/database_scripts/database_scripts/protonyms_with_notes_taxt.rb
app/database_scripts/database_scripts/protonyms_with_primary_type_information_taxt.rb
app/database_scripts/database_scripts/protonyms_with_secondary_type_information_taxt.rb
app/database_scripts/database_scripts/protonyms_with_type_notes_taxt.rb
app/database_scripts/database_scripts/types_of_genus_group_names.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/58

More 3.6.8 tweaks

---

.rubocop.yml
app/controllers/institutions_controller.rb
app/decorators/institution_decorator.rb
app/models/institution.rb
app/services/types/expand_institution_abbreviations.rb
app/views/institutions/_form.haml
app/views/institutions/index.haml
app/views/institutions/show.haml
db/migrate/20201120215842_add_grscicoll_identifier_to_institutions.rb
db/schema.rb
spec/controllers/institutions_controller_spec.rb
spec/decorators/institution_decorator_spec.rb
spec/models/institution_spec.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/80

GRSciColl identifiers and links for institutions

---

app/assets/stylesheets/site/_global.sass
app/database_scripts/database_scripts/protonyms_with_etymology_taxt.rb
app/forms/protonym_form.rb
app/models/protonym.rb
app/models/rank.rb
app/views/catalog/_show/logged_in_only/_editors_sidebar.haml
app/views/protonyms/_form.haml
app/views/protonyms/shared/_etymology_and_gender.haml
app/views/protonyms/show.haml
app/views/taxa/_form/_create_new_protonym_form.haml
app/views/taxa/_form/_main_form.haml
db/migrate/20201204224242_add_gender_agreement_type_to_protonyms.rb
db/schema.rb
spec/controllers/protonyms_controller_spec.rb
spec/factories/protonym_params.rb
spec/factories/protonyms.rb
spec/models/protonym_spec.rb
spec/models/rank_spec.rb

Closes-ish https://github.com/calacademy-research/antcat-issues/issues/85 and https://github.com/calacademy-research/antcat-issues/issues/70

Gender agreement types for protonyms (changeable / unchangeable)

---

app/controllers/taxa/force_updates_controller.rb
app/helpers/application_helper.rb
app/models/activity.rb
app/views/activities/templates/actions/_force_update_database_record.haml
app/views/catalog/_show/_editor_buttons.haml
app/views/taxa/force_updates/show.haml
config/breadcrumbs/taxa.rb
config/routes.rb
spec/controllers/taxa/force_updates_controller_spec.rb
spec/decorators/activity_decorator_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/86

Form for force-updating taxon records

---

.github/workflows/main.yml
Gemfile
Gemfile.lock
docker/antcat-database.docker
lib/service.rb
spec/controllers/protonyms/autocompletes_controller_spec.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/89

Ruby 2.7.1 upgrade

---

app/models/protonyms/what_links_here.rb
app/models/references/what_links_here.rb
app/models/taxa/what_links_here.rb
app/models/what_links_here_item.rb
spec/models/protonyms/what_links_here_spec.rb
spec/models/references/what_links_here_spec.rb
spec/models/taxa/what_links_here_spec.rb
spec/models/what_links_here_item_spec.rb

What Links Here for relational history items

---

app/injectable_formatters/antweb_formatter/detax.rb
app/models/taxt.rb
app/services/markdowns/parse_catalog_tags.rb
app/views/shared/_markdown_formatting_help.haml
spec/injectable_formatters/antweb_formatter/detax_spec.rb
spec/models/protonyms/what_links_here_spec.rb
spec/services/markdowns/parse_catalog_tags_spec.rb

Add new taxt tag: 'prottac': Protonym Terminal Taxon with Author Citation

---

app/assets/javascripts/logged_in_only/history_item_form.coffee
app/controllers/history_items_controller.rb
app/models/history_item.rb
app/views/history_items/_form.haml
db/migrate/20201221204003_add_force_author_citation_to_history_items.rb
db/schema.rb
lib/tasks/seed/relational_history_items.rb
spec/factories/history_items.rb
spec/models/history_item_spec.rb

"Force author citations" checkbox for relational history items

---

app/assets/javascripts/logged_in_only/history_item_form.coffee
app/database_scripts/database_scripts/replacement_name_history_items_missing.rb
app/models/history_item.rb
app/views/history_items/_form.haml
app/views/history_items/edit_templates/_replacement_name.haml
app/views/history_items/edit_templates/_replacement_name_for.haml
app/views/history_items/edit_templates/_unavailable_name.haml
lib/tasks/seed/relational_history_items.rb
spec/factories/history_items.rb
spec/models/history_item_spec.rb
spec/presenters/history_presenter_spec.rb

Add relational history item definitions: ReplacementName, ReplacementNameFor and UnavailableName

---

app/assets/stylesheets/controllers/_history_items.sass
app/controllers/history_items_controller.rb
app/controllers/references_controller.rb
app/database_scripts/database_scripts/protonyms_by_number_of_history_items.rb
app/database_scripts/database_scripts/protonyms_by_number_of_history_items_as_object.rb
app/database_scripts/database_scripts/protonyms_by_number_of_taxt_history_items.rb
app/database_scripts/database_scripts/replacement_name_for_history_items_disagreeing.rb
app/database_scripts/database_scripts/replacement_name_history_items_disagreeing.rb
app/decorators/history_item_decorator.rb
app/models/grouped_history_item.rb
app/models/history_item.rb
app/models/protonym.rb
app/views/catalog/_show/_taxon_description.haml
app/views/history_items/_catalog_taxt_editor_template.haml
app/views/history_items/index.haml
app/views/history_items/show.haml
app/views/protonyms/show.haml
app/views/references/show.haml
spec/models/history_item_spec.rb

3.7.1.1 history grab bag

---

docker/download-database.sh

```
ssh deploy@antcat.org sudo -i eybackup --list-backup antcat
Listing database backups for antcat
6 backup(s) found
0:antcat antcat.2020-12-22T10-15-03.sql.gz
1:antcat antcat.2020-12-23T10-15-02.sql.gz
2:antcat antcat.2020-12-24T10-15-03.sql.gz
3:antcat antcat.2020-12-25T10-15-02.sql.gz
4:antcat antcat.2020-12-26T10-15-02.sql.gz
5:antcat antcat.2020-12-27T10-15-02.sql.gz
```

Fix AntWeb export when run on new instances

---

app/assets/javascripts/application.js
app/assets/javascripts/globals/create_copy_buttons.js
app/assets/stylesheets/controllers/_references.sass
app/assets/stylesheets/site/_global.sass
app/decorators/type_name_decorator.rb
app/helpers/copy_to_clipboard_helper.rb
app/models/database_scripts/render_helpers.rb
app/models/taxt.rb
app/presenters/editors/reference_presenter.rb
app/services/markdowns/bolton_keys_to_ref_tags.rb
app/services/markdowns/parse_catalog_tags.rb
app/services/taxa/collect_references.rb
app/services/taxt/convert_tags.rb
app/views/catalog/_show/_taxon_description.haml
app/views/catalog/_show/logged_in_only/_editors_sidebar.haml
app/views/protonyms/show.haml
app/views/references/show.haml
app/views/shared/_markdown_formatting_help.haml
config/initializers/assets.rb
spec/models/taxt_spec.rb

First step of https://github.com/calacademy-research/antcat-issues/issues/1 and https://github.com/calacademy-research/antcat-issues/issues/2

Copy taxt tags to clipboard

---

app/forms/reference_form.rb
app/models/author_name.rb
app/models/reference.rb
app/models/references/concerns/searchable.rb
app/presenters/revision_presenter.rb
db/migrate/20201231084512_add_key_with_suffixed_year_cache_to_references.rb
db/schema.rb
lib/tasks/antcat/reference_caches.rake
spec/factories/references.rb
spec/models/reference_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/91

Add `references.key_with_suffixed_year_cache`

---

app/javascript/packs/components/TestDirective.vue
app/javascript/packs/vue_app.js
app/views/layouts/application.haml
app/views/pages/about.html.haml

Fix for #1226
Fixes:
```
Compilation failed:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.entry should be an non-empty object.
-> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
```

fix(webpacker): add js files to fix compilation step

---

app/models/reference.rb
app/presenters/revision_presenter.rb
db/migrate/20210116180528_remove_nomen_attributes_from_protonyms.rb
db/migrate/20210116180813_remove_expandable_reference_cache_from_references.rb
db/schema.rb

Cleanup after https://github.com/calacademy-research/antcat/pull/1235 and https://github.com/calacademy-research/antcat/pull/1234

Remove unused protonyms and references columns

---

app/database_scripts/database_scripts/genera_with_names_that_are_different_from_their_protonyms_name.rb
app/database_scripts/database_scripts/history_items_starting_with_lower_case_letters.rb
app/database_scripts/database_scripts/history_items_with_commas_before_ref_tags.rb
app/database_scripts/database_scripts/history_items_with_hardcoded_names_genus_batch1.rb
app/database_scripts/database_scripts/history_items_with_hardcoded_names_genus_batch2.rb
app/database_scripts/database_scripts/history_items_with_hardcoded_names_genus_batch3.rb
app/database_scripts/database_scripts/history_items_with_hardcoded_names_subfamily_batch1.rb
app/database_scripts/database_scripts/history_items_with_hardcoded_names_tribe_batch1.rb
app/database_scripts/database_scripts/history_items_with_long_pages.rb
app/database_scripts/database_scripts/history_items_with_pages_containing_weird_characters.rb
app/database_scripts/database_scripts/junior_synonym_of_history_items_missing.rb
app/database_scripts/database_scripts/missing_taxa_to_be_created.rb
app/database_scripts/database_scripts/most_recent_before_now_taxon_investigation.rb
app/database_scripts/database_scripts/non_standard_replacement_name_history_items.rb
app/database_scripts/database_scripts/protonyms_with_rank_specific_and_unranked_history_items.rb
app/database_scripts/database_scripts/species_group_protonyms_without_biogeographic_regions.rb
app/database_scripts/database_scripts/synonyms_at_different_ranks_only_species_and_below.rb
app/database_scripts/database_scripts/taxa_that_appears_more_than_once_in_type_names.rb
app/models/database_scripts/tagging.rb
app/views/database_scripts/index.haml

For https://github.com/calacademy-research/antcat-issues/issues/27

3.7.5.2 db scripts

---

app/decorators/protonym_decorator.rb
app/forms/protonym_form.rb
app/views/protonyms/_form.haml
app/views/taxa/_form/_create_new_protonym_form.haml
db/migrate/20200501210906_add_uncertain_locality_to_protonyms.rb
spec/decorators/protonym_decorator_spec.rb
spec/exporters/exporters/antweb/history/protonym_synopsis/protonym_line_spec.rb
spec/factories/protonyms.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/100

Remove "Uncertain locality" from protonyms

---

db/migrate/20200501210906_add_uncertain_locality_to_protonyms.rb
db/migrate/20210220225054_remove_uncertain_locality_from_protonyms.rb
db/schema.rb

Remove unused column `protonyms.uncertain_locality`

---

app/models/reference.rb
db/migrate/20210402200514_add_normalized_bolton_key_to_references.rb
db/schema.rb
spec/models/reference_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/101

Add `references.normalized_bolton_key`

---

Gemfile
Gemfile.lock
app/assets/config/manifest.js
app/assets/stylesheets/_settings.scss
config/initializers/assets.rb

See https://sass-lang.com/blog/ruby-sass-is-deprecated

Upgrade Sprockets and migrate to Sassc

---

app/controllers/database_scripts_controller.rb
app/models/database_script.rb
app/presenters/database_scripts_presenter.rb
app/views/database_scripts/index.haml
spec/models/database_script_spec.rb
spec/presenters/database_scripts_presenter_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/113

Filter database scripts by tag

---

app/models/reference_document.rb

For https://github.com/calacademy-research/antcat-issues/issues/114

Preserve reference document files on S3

---

app/models/reference_document.rb
config/settings/development.yml
config/settings/production.secret.yml.example
config/settings/staging.secret.yml.example
config/settings/test.yml

Bonus commit for https://github.com/calacademy-research/antcat-issues/issues/114

Move S3 bucket/region config to `Settings`

---

.rubocop.yml
app/assets/javascripts/logged_in_only/history_item_form.coffee
app/cleanup/taxt/standard_history_item_formats.rb
app/database_scripts/database_scripts/combination_in_history_items_with_non_genus_group_taxon_as_object_taxon.rb
app/database_scripts/database_scripts/protonyms_by_number_of_history_items.rb
app/database_scripts/database_scripts/protonyms_by_number_of_history_items_as_object.rb
app/database_scripts/database_scripts/protonyms_by_number_of_taxt_history_items.rb
app/database_scripts/database_scripts/subspecies_of_history_items_with_non_species_as_terminal_taxon.rb
app/database_scripts/database_scripts/unpaired_junior_synonym_of_history_items.rb
app/database_scripts/database_scripts/unpaired_senior_synonym_of_history_items.rb
app/helpers/dev_helper.rb
app/models/history/definitions.rb
app/models/history_item.rb
app/views/application/_navigation.haml
spec/models/history_item_spec.rb

Meta-issue: https://github.com/calacademy-research/antcat-issues/issues/19

3.7.7.3 history updates

---

app/database_scripts/database_scripts/peculiar_and_interesting_cases.rb
app/database_scripts/database_scripts/replacement_name_for_history_items_disagreeing.rb
app/database_scripts/database_scripts/replacement_name_for_history_items_missing.rb
app/database_scripts/database_scripts/replacement_name_history_items_disagreeing.rb
app/database_scripts/database_scripts/replacement_names.rb
app/models/database_scripts/render_helpers.rb
app/models/taxon.rb

For https://github.com/calacademy-research/antcat-issues/issues/43, https://github.com/calacademy-research/antcat-issues/issues/67, https://github.com/calacademy-research/antcat-issues/issues/82

Database scripts: Replacement names-related

---

app/assets/stylesheets/foundation_and_overrides.sass
app/decorators/database_script_decorator.rb
app/views/database_scripts/index.haml
app/views/database_scripts/show.haml
spec/decorators/database_script_decorator_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/113

Database scripts UX improvements

---

app/assets/javascripts/logged_in_only/history_item_form.coffee
app/models/history/definitions.rb
app/views/history_items/_form.haml
app/views/history_items/edit_templates/_homonym_replaced_by.haml
app/views/history_items/edit_templates/_replacement_name_for.haml
lib/tasks/seed/relational_history_items.rb
spec/factories/history_items.rb
spec/models/history_item_spec.rb

Make `HomonymReplacedBy` and `ReplacementNameFor` items taxon-based

---

.rubocop.yml
app/assets/javascripts/logged_in_only/history_item_form.coffee
app/controllers/quick_and_dirty_fixes_controller.rb
app/database_scripts/database_scripts/replacement_name_for_history_items_with_duplicated_foreign_data.rb
app/database_scripts/database_scripts/replacement_name_for_history_items_with_duplicated_sibling_items.rb
app/models/database_scripts/render_helpers.rb
app/models/history/definitions.rb
app/models/history_item.rb
app/views/history_items/edit_templates/_junior_primary_homonym_of.haml
app/views/history_items/edit_templates/_junior_primary_homonym_of_hardcoded_genus.haml
app/views/history_items/edit_templates/_junior_secondary_homonym_of.haml
config/routes.rb
spec/factories/history_items.rb
spec/models/history_item_spec.rb

Add types for relational 'Junior homonym of' history items x 3

---

app/services/taxa/statistics/fetch_statistics.rb
db/migrate/20210730182739_remove_fossil_from_taxa.rb
db/migrate/20210730183416_remove_public_from_reference_documents.rb
db/migrate/20210730183547_remove_hong_from_taxa.rb
db/schema.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/122, https://github.com/calacademy-research/antcat-issues/issues/123, https://github.com/calacademy-research/antcat-issues/issues/124

Remove deprecated db columns: `taxa.fossil`, `taxa.hong`, `reference_documents.public`

---

.gitignore
Dockerfile.dev
INSTALL.md
docker-compose.yml
docker_dev/README.md
docker_dev/database.docker-dev.yml
features/support/env.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/121

Add Docker development container

---

app/assets/javascripts/all_pages/reference_autocompletion.coffee
app/controllers/authors/autocompletes_controller.rb
app/queries/autocomplete/author_names_query.rb
spec/controllers/authors/autocompletes_controller_spec.rb
spec/queries/autocomplete/author_names_query_spec.rb
spec/support/json_response_helper.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/126

Fix broken author autocompletion (header search box)

---

app/models/activity.rb
db/migrate/20220408190142_add_event_to_activities.rb
db/migrate/20220413164737_add_not_null_to_activities_event.rb
db/migrate/20220413170109_remove_action_from_activities.rb
db/schema.rb

Rename `activities.action` (part 3, remove old column)

---

app/services/notifications/notify_user.rb
app/views/devise/passwords/new.haml
app/views/devise/sessions/new.haml
config/settings.yml
features/notifications/email_notifications.feature
features/users/forgot_password.feature
spec/services/notifications/notify_user_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/131

Disable email deliveries (currently broken)

---

app/assets/javascripts/application.js
app/assets/stylesheets/foundation_and_overrides.sass
app/assets/stylesheets/site/_layout.sass
app/assets/stylesheets/site/_taxon_browser.sass
app/views/catalog/_show/_taxon_browser.haml
app/views/layouts/application.haml

For https://github.com/calacademy-research/antcat-issues/issues/130

Taxon Browser: Replace Zurb Foundation sticky with CSS

---

.eslintrc.json
.rubocop.yml
app/assets/javascripts/markdown_and_friends/preview_markdown.coffee
app/assets/stylesheets/site/_global.sass
app/assets/stylesheets/site/_hover_preview.sass
app/decorators/protonym_decorator.rb
app/decorators/reference_decorator.rb
app/decorators/taxon_decorator.rb
app/injectable_formatters/catalog_formatter.rb
app/javascript/controllers/hover_preview_controller.js
app/javascript/packs/hotwire_app.js
app/javascript/packs/vue_app.js
package.json
spec/support/test_links_helpers.rb
yarn.lock

For https://github.com/calacademy-research/antcat-issues/issues/132

Rewrite hover previews in Stimulus

---

Gemfile
Gemfile.lock
config/application.rb

CHANGELOG: https://github.com/paper-trail-gem/paper_trail/blob/master/CHANGELOG.md#1400-2022-11-26

gems: update to paper_trail 14

---

.github/workflows/main.yml
config/database.github-actions.yml

Deprecated, see https://github.com/actions/runner-images/issues/6002
For debugging (via https://github.com/actions/runner-images/issues/2889):
```
- name: Show mysql version 1
run: mysql --host 127.0.0.1 --port 33306 -uroot -proot -e "SELECT @@VERSION"
- name: Show mysql version 2
run: |
echo 'SELECT VERSION();' | bundle exec rails db -p
```

Upgrade GitHub Actions image since ubuntu-18.04 is deprecated

---

app/assets/stylesheets/foundation_and_overrides.sass
app/assets/stylesheets/site/_global.sass
app/assets/stylesheets/site/_global2.sass
app/helpers/application_helper.rb
app/views/application/_flash_messages.html.haml
app/views/catalog/_show/_taxon_browser.html.haml
app/views/catalog/_show/logged_in_only/_editors_sidebar.html.haml
app/views/catalog/searches/_results.html.haml
app/views/catalog/soft_validations/show.html.haml
app/views/devise/passwords/new.html.haml
app/views/editors_panels/show.html.haml
app/views/editors_panels/versions/index.html.haml
app/views/feedbacks/show.html.haml
app/views/issues/index.html.haml
app/views/names/_form.html.haml
app/views/protonyms/show.html.haml
app/views/references/search/index.html.haml
app/views/shared/_errors_for.html.haml
app/views/shared/_operation_not_supported.html.haml
app/views/taxa/_form.html.haml
app/views/taxa/force_parent_changes/show.html.haml
app/views/taxa/force_updates/show.html.haml
app/views/users/show.html.haml
spec/helpers/application_helper_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/130

Rewrite Zurb Foundation styles in Sass

---

app/assets/stylesheets/_colors.sass
app/assets/stylesheets/application.sass
app/assets/stylesheets/controllers/_activities.sass
app/assets/stylesheets/controllers/_references.sass
app/assets/stylesheets/foundation_old.scss
app/assets/stylesheets/site/_global.sass
app/assets/stylesheets/site/_global2.sass
app/assets/stylesheets/site/_hover_preview.sass
app/assets/stylesheets/site/_layout.sass
app/assets/stylesheets/site/_markdown_preview.sass
app/assets/stylesheets/site/_taxt_editor.sass
app/assets/stylesheets/site/_tooltip2.sass
app/assets/stylesheets/site/_widgets.sass
app/assets/stylesheets/vendor_and_customizations.sass
app/assets/stylesheets/vendor_customizations/_atwho.sass
app/assets/stylesheets/vendor_customizations/_font_awesome_and_custom_icons.sass
app/views/activities/_table.html.haml

For https://github.com/calacademy-research/antcat-issues/issues/130
Follow-up to #1459

Cleanup CSS part V (colors and merge files)

---

.github/workflows/main.yml
.haml-lint.yml
.rubocop.yml
Dockerfile.dev
Gemfile
Gemfile.lock
docker/antcat-database.docker

TODO:
Before:
```
ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
```

Update to Ruby 3.1.2

---

app/assets/stylesheets/site/_hover_preview.sass
app/javascript/controllers/external_preview_controller.js
app/services/types/link_specimen_identifiers.rb
spec/services/types/link_specimen_identifiers_spec.rb

Closes https://github.com/calacademy-research/antcat-issues/issues/68

Add hover previews for AntWeb specimen links

---

app/assets/stylesheets/foundation_old.scss
app/assets/stylesheets/site/_global.sass
app/assets/stylesheets/site/_global2.sass
app/assets/stylesheets/site/_markdown_preview.sass
app/assets/stylesheets/site/_navigation.sass
app/assets/stylesheets/site/_reference_table.sass
app/assets/stylesheets/site/_taxon_browser.sass
app/assets/stylesheets/site/_widgets.sass
app/helpers/dev_helper.rb
app/views/application/_footer.html.haml
app/views/application/_navigation.html.haml
app/views/catalog/_show/_taxon_browser.html.haml
app/views/history_items/_form.html.haml
app/views/history_items/edit_templates/_form_descriptions.html.haml
app/views/history_items/edit_templates/_type_specimen_designation.html.haml
app/views/layouts/_trigger_tailwind_classes.html.haml
app/views/layouts/application.html.haml
app/views/pages/about.html.haml
app/views/protonyms/_form.html.haml
app/views/shared/taxt_editor/_taxt_editor_template.html.haml
app/views/taxa/_form/_create_new_protonym_form.html.haml
app/views/taxa/_form/_main_form.html.haml
app/views/users/show.html.haml
config/tailwind.config.js
spec/services/types/link_specimen_identifiers_spec.rb

For https://github.com/calacademy-research/antcat-issues/issues/130

Cleanup CSS part IV

---

Gemfile
Gemfile.lock
app/assets/images/icons/bars-3.svg
app/assets/images/icons/chevron-down.svg
app/assets/images/icons/magnifying-glass.svg
app/assets/stylesheets/site/_widgets.sass
app/views/application/_navigation.html.haml
app/views/catalog/_show/_breadcrumbs_right.html.haml
app/views/history_items/index.html.haml
app/views/protonyms/show.html.haml
app/views/reference_sections/index.html.haml
app/views/references/show.html.haml
config/initializers/inline_svg.rb
config/tailwind.config.js

https://github.com/jamesmartin/inline_svg

Add gem `inline_svg` and SVG icons
