lib/database_scripts/renderers/markdown.rb, lib/database_scripts/scripts/missing_references_in_protonym_authorships.rb
http://antcat.org/database_scripts/missing_references_in_protonym_authorships does not render because `Protonym.find(164534)`'s `has_one :taxon` has been deleted.
=> Fix db script 'Missing references in protonym authorships'

app/assets/stylesheets/controllers/_catalog.sass, app/decorators/taxon_decorator.rb, app/views/catalog/_reference_sections.haml, app/views/catalog/_taxon_description.haml, lib/exporters/antweb/export_reference_sections.rb, lib/exporters/antweb/exporter.rb
- Link reference sections (to make their revision histories browsable)
- Extract/split AntWeb export-related code to make the above change possible
- Slightly change the format/style of the links to the revision histories
CI is green: https://travis-ci.org/jonkerz/antcat/builds/240161312?utm_source=github_status&utm_medium=notification
=> Link reference sections

app/decorators/taxon_decorator/statistics.rb, spec/decorators/taxon_decorator/statistics_spec.rb
=> feat: Tweak to avoid "(synonyms)" without context

app/models/reference.rb, solr/conf/schema.xml
Issue: #90 
I'm not sure which field to use for this, but the original issue is: given a reference with the doi "10.1111/syen.12253", searching for "10.1111" yields no results without something like this.
Note: I've no idea what I'm doing.
=> fix: Attempt to fix DOI search in Solr

app/controllers/site_notices_controller.rb, app/views/site_notices/_form.haml, app/views/site_notices/_unread_site_notices_flash_message.haml, app/views/site_notices/index.haml, app/views/site_notices/show.haml, db/migrate/20171001164413_remove_blurb_from_site_notices.rb, db/schema.rb, features/editors_panel/site_notices.feature
Simpler, we don't really need it.
=> feat: Remove 'blurb' from site notices

app/controllers/references_controller.rb
Closes #352.
Broke in a32b31ef34890d411ec98f723d6d27a62f8ff9c6.
=> fix: Missing PDF file param

app/controllers/editors_panels/versions_controller.rb, app/decorators/change_decorator.rb, app/models/change.rb, app/views/changes/_change.haml, app/views/changes/_table_header.haml, db/migrate/20171231030837_add_user_to_changes.rb, db/schema.rb, features/step_definitions/changes_steps.rb, lib/undo_tracker.rb, spec/factories/changes.rb, spec/models/change_spec.rb, spec/models/taxa/taxon_workflow_spec.rb
Issue: #359 
So I looked into this and the reason we're showing the wrong editor is because to find the editor responsible for the change, the code looks for the editor in PaperTrail versions associated with the change. If there are no such versions (for example if you just save the form without making any changes), the code searches in the history of the taxon, which is why we always get the second most recent editor when this happens.
Changes:
* For new edits: Directly associate the correct user with the change.
* For old edits: Remove backwards compatability code so that we're not showing the wrong editor (it will just say "Someone" instead)
* For debugging purposes: Show the number of PaperTrail versions in the change list, so that we can figure out if A) we should not create these …
=> Change attribution

app/assets/javascripts/all_pages/global.coffee, app/assets/stylesheets/site/_global.sass, app/database_scripts/database_scripts/taxa_with_type_fields.rb, app/decorators/activity_decorator.rb, app/decorators/reference_decorator/nested_reference_decorator.rb, app/services/exporters/antweb/type_fields.rb, app/views/activities/templates/_feedback.haml, app/views/catalog/_type_fields.haml, app/views/editors_panels/index.haml, app/views/pages/lazy_links.html.haml, app/views/taxa/form/_type_section.haml, features/feed/feedback_activities.feature, features/feed/user_activities.feature, spec/decorators/activity_decorator_spec.rb
Truncates any type field at 500 characters (the limit is set to 200 in the screenshots, and "Primary type information" is not included since that change had not been done at the time the screenshots were taken).
Also closes #370.
=> Tech: 2.5.4 tweaks

app/assets/javascripts/controllers/taxa/form/form.coffee, app/assets/javascripts/reference_select.coffee, app/assets/javascripts/widgets/reference_field.coffee, app/assets/stylesheets/controllers/_taxa.sass, app/controllers/references_controller.rb, app/controllers/taxa_controller.rb, app/helpers/reference_select_helper.rb, app/services/autocomplete/autocomplete_references.rb, app/services/taxa/save_from_form.rb, app/views/taxa/_form.haml, app/views/taxa/form/_protonym_section.haml, features/changes/changes.feature, features/feed/taxon_activities.feature, features/step_definitions/edit_steps/edit_steps.rb, features/taxon_form/add_taxon_successfully.feature, features/taxon_form/edit_taxon.feature, features/widgets/default_reference.feature, spec/services/taxa/save_from_form_spec.rb
This is for reference buttons (protonym reference etc); the reference selector in the taxt editor will be updated in #377.
Closes: #117.
=> New reference selector

app/controllers/name_fields_controller.rb, app/models/name.rb
Issue: #556
TODO:
```ruby
jonkerz = User.find 60
Activity.execute_script_activity jonkerz, 'Fix trailing spaces in names, see %github556'
Name.where("name LIKE '% '").find_each do |name| name.save end
```
=> fix: Trim trailing spaces from `Name#name`

app/database_scripts/database_scripts/epi_and_questionmark_taxt_tags.rb, app/database_scripts/database_scripts/nam_taxt_tags.rb, app/models/concerns/taxa/callbacks_and_validations.rb, app/services/exporters/antweb/export_taxon.rb, app/services/taxa/copy_attributes.rb, app/views/catalog/_taxon_description.haml, lib/taxt.rb, public/api/v1/swagger.yaml, spec/services/names/what_links_here_spec.rb, spec/services/references/what_links_here_spec.rb, spec/services/taxa/convert_to_subspecies_spec.rb, spec/services/taxa/copy_attributes_spec.rb, spec/services/taxa/elevate_to_species_spec.rb
See https://github.com/calacademy-research/antcat/issues/512
It was only being used for six taxa (which has been migrated) and it could not be changed in the GUI.
=> remove: taxon.genus_species_header_notes_taxt

app/models/reference.rb, db/migrate/20190331150031_remove_unused_columns.rb, db/schema.rb
See https://github.com/calacademy-research/antcat/issues/461
Removed:
`taxa.genus_species_header_notes_taxt`
`taxa.display`
`references.principal_author_last_name_cache`
`names.protonym_html`
=> Remove unused columns

db/migrate/20171022020010_add_type_fields_to_taxa.rb, db/migrate/20190108035206_add_type_taxon_id_to_taxa.rb, db/migrate/20190402204649_remove_unused_type_columns_from_taxa.rb, db/schema.rb
See #461
Columns:
* `taxa.type_name_id`
* `taxa.type_fossil`
* `taxa.verbatim_type_locality`
* `taxa.type_specimen_repository`
* `taxa.type_specimen_code`
* `taxa.type_specimen_url`
=> Remove unused taxon type columns

app/controllers/taxa/convert_to_subspecies_controller.rb, app/controllers/taxa/elevate_to_species_controller.rb, app/decorators/taxon_decorator/link_each_epithet.rb, app/helpers/taxon_select_helper.rb, app/models/concerns/taxa/callbacks_and_validations.rb, app/models/name.rb, app/models/names/genus_group_name.rb, app/models/names/species_group_name.rb, app/services/names/picklist_matching.rb, app/views/taxa/create_obsolete_combinations/show.haml, db/migrate/20150805233239_remove_nonstandard_notation.rb, db/migrate/20150811165357_remove_protonym_html.rb, public/api/v1/swagger.yaml, spec/decorators/table_ref_decorator_spec.rb, spec/models/name_spec.rb, spec/models/taxa/species_group/subspecies_spec.rb, spec/services/names/create_name_from_string_spec.rb, spec/services/names/picklist_matching_spec.rb, spec/services/taxa/create_obsolete_combination_spec.rb
Meta issue: #604
Changes `Name#name_html` (attribute, now unused) -->  `Name#name_to_html` (method)
Any other reference that includes the word `name_html` are left as is. The plan is to drop `names.name_html` and rename the method to `#name_html`. Same thing with `Name#epithet_html`.
This will make creating names easier.
=> Dynamic HTML names - part 1

app/assets/javascripts/check_name_conflicts.coffee, app/assets/stylesheets/widgets/_check_name_conflicts.sass, app/controllers/names/check_name_conflicts_controller.rb, app/models/name.rb, app/services/names/find_conflicts.rb, app/views/names/_form.haml, config/routes.rb, features/names/manage.feature, features/step_definitions/protonym_steps.rb, spec/controllers/names/check_name_conflicts_controller_spec.rb
Meta issue: #604
This will be used in the taxon form, but we want to disable editing names in the taxon and protonym forms before that, and before that we want to dedup name records (#662).
=> Check name conflicts in name form

app/controllers/references/replace_missing_controller.rb, app/database_scripts/database_scripts/missing_references.rb, app/helpers/reference_select_helper.rb, app/helpers/taxon_helper.rb, app/models/activity.rb, app/services/references/replace_missing.rb, app/views/activities/templates/actions/_replace_missing_reference.haml, app/views/references/replace_missing/show.haml, app/views/references/show.haml, config/breadcrumbs/references.rb, config/routes.rb
Closes #661
No specs, since it's Temporary Code(tm) we can remove once  http://antcat.org/database_scripts/missing_references has been cleared.
---
=> Replace missing reference button (AntCat 3.0.24)

app/assets/javascripts/taxt_editor.coffee
Site notice draft
---
Taxt editor fix (AntCat 3.0.32)
* Fix issue with the taxt editor firing events multiple times (%github701)
=> fix: Multiple JS click bindings

app/controllers/application_controller.rb, app/controllers/editors_panels/versions_controller.rb, app/models/activity.rb, app/models/concerns/set_request_uuid.rb, app/models/paper_trail/version.rb, app/views/activities/_table.haml, app/views/editors_panels/versions/index.haml, db/migrate/20200124181539_add_request_uuid_to_versions_and_activities.rb, db/schema.rb, spec/models/activity_spec.rb, spec/models/paper_trail/version_spec.rb, spec/requests/application_controller_spec.rb, spec/support/rspec.rb, spec/support/shared_examples.rb
To be able to track all changes that were created during a particular request. Useful for investigating complicated changes, and for reversing a change.
=> Associate activities and versions with the request

app/models/reference.rb, spec/controllers/my/recently_used_references_controller_spec.rb, spec/factories/references.rb, spec/models/reference_spec.rb, spec/models/taxon_spec.rb, spec/services/exporters/endnote/formatter_spec.rb, spec/services/markdowns/bolton_keys_to_ref_tags_spec.rb, spec/services/references/search/fulltext_spec.rb, spec/services/taxa/search/advanced_search_spec.rb, spec/services/wikipedia/reference_exporter_spec.rb
Now only `MissingReference`s are allowed to not have any authors associated with the reference.
=> Validate reference author names

app/assets/javascripts/controllers/taxa/reorder_history_items.coffee, app/assets/javascripts/controllers/taxa/reorder_reference_sections.coffee, app/controllers/taxa/reorder_history_items_controller.rb, app/controllers/taxa/reorder_reference_sections_controller.rb, app/models/activity.rb, app/services/taxa/operations/reorder_history_items.rb, app/services/taxa/operations/reorder_reference_sections.rb, app/views/activities/templates/actions/_reorder_reference_sections.haml, app/views/taxa/_not_really_form/_history_items_section.haml, app/views/taxa/_not_really_form/_references_section.haml, app/views/taxa/edit.haml, config/initializers/assets.rb, config/routes.rb, spec/controllers/taxa/reorder_reference_sections_controller_spec.rb, spec/services/taxa/operations/reorder_reference_sections_spec.rb
Copy-pasta of the code for reordering history items because a) it was very
easy, b) we don't care too much about this code since it will be
replaced once we migrate to more relational reference sections.
=> Reorder reference sections

app/controllers/references_controller.rb, app/formatters/reference_formatter.rb, app/forms/reference_form.rb, app/models/reference.rb, app/models/references/nested_reference.rb, app/services/authors/find_or_initialize_names_from_string.rb, app/services/autocomplete/format_linkable_references.rb, app/services/references/new_from_copy.rb, app/views/references/_form.haml, app/views/references/edit.haml, app/views/references/new.haml, app/views/references/show.haml, db/migrate/20200202204901_copy_references_pages_in_to_pagination.rb, db/schema.rb, features/reference_form/add_reference_successfully.feature, features/reference_form/add_reference_unsuccessfully.feature, features/reference_form/copy_reference.feature, features/reference_form/duplicate_checking.feature, features/reference_form/edit_reference_successfully.feature, features/reference_form/new_nested_reference_button.feature, features/step_definitions/reference_steps.rb, spec/controllers/references_controller_spec.rb, spec/factories/references.rb, spec/formatters/reference_formatter_spec.rb, spec/forms/reference_form_spec.rb, spec/models/references/nested_reference_spec.rb, spec/services/authors/find_or_initialize_names_from_string_spec.rb, spec/services/autocomplete/format_linkable_references_spec.rb, spec/services/references/new_from_copy_spec.rb
Refactor and refactor-ish to make all `Reference`s use pagination in a consistent manner.
Changes:
- Use `pagination` for all types of references. We don't need to separate book/article pagination in the form, and we want use pagination for `UnknownReferences` too. That only leaves `NestedReference`s which are currently using `references.pages_in` but never `references.pagination`, so we might as well merge the columns.
- Other smaller tweaks.
I believe the article/book pagination was a special case due to how fields are conditionally hidden/shown in the reference form, but it makes the class responsible for saving references more complicated than what it needs to be.
More work is required here, but I think this is enough for this session.
Short version: Use the `pagination` column and …
=> Refactor reference form (pagination)

app/controllers/references_controller.rb, app/database_scripts/database_scripts/reference_documents_with_weird_actual_urls.rb, app/decorators/reference_decorator.rb, app/decorators/reference_decorator/nested_reference_decorator.rb, app/forms/reference_form.rb, app/models/reference.rb, app/models/reference_document.rb, app/services/exporters/endnote/formatter.rb, app/services/wikipedia/reference_exporter.rb, app/views/references/_form.haml, features/references/search_references.feature, features/step_definitions/reference_steps.rb, features/widgets/taxon_selector.feature, spec/decorators/reference_decorator_spec.rb, spec/forms/reference_form_spec.rb, spec/models/cached_reference_formatter_spec.rb, spec/models/reference_document_spec.rb, spec/models/reference_spec.rb, spec/services/exporters/antweb/antweb_inline_citation_spec.rb
Meta issue: #924
Changes:
* Validate protocol of URLs instead of adding it to the `url`.
* Dynamically generate "antcat.org routed" document links instead of inserting `host` in the `url`.
* Show ID of reference document and `file_file_name` in the reference form.
* Update reference documents in place, to avoid creating new reference documents records when saving references (with out without making any changes).
* Clear document URL when new PDFs are uploaded (we cannot always clear them yet).
* References can already have both an uploaded file and a URL (see %dbscript:ReferenceDocumentsWithWeirdActualUrls). A new notice is shown in the reference form for such cases. The blue one can be ignored. We want to deal with these later. The same rules are before apply: link any uploaded file …
=> Tweak ReferenceDocument

app/helpers/application_helper.rb, public/robots.txt, spec/decorators/reference_decorator_spec.rb, spec/injectable_formatters/antweb_formatter/reference_link_spec.rb, spec/services/references/formatted/expandable_spec.rb
From today:
```
awk -F"\"" '{print $6}' /var/log/nginx/antcat.ssl.access.log | sort | uniq -dc | sort -nr
5581 Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)
5273 Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +http://megaindex.com/crawler)
3163 Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)
2024 Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)
1286 Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)
963 Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)
731 Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; AspiegelBot)
679 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) …
```
=> Disallow more bots

db/migrate/20200526215213_remove_type_taxt_and_type_taxon_id_from_taxa.rb, db/migrate/20200526215518_remove_headline_notes_taxt_from_taxa.rb, db/migrate/20200526215649_remove_citation_from_references.rb, db/migrate/20200526221743_drop_changes_and_taxon_states_tables.rb, db/schema.rb
Closes #1026.
* `taxa.headline_notes_taxt`
* `references.citation`
* `taxa.type_taxon_id` and `taxa.type_taxt`
* table `taxon_states`
* table `changes`
=> Remove unused database tables and columns

app/database_scripts/database_scripts/fossil_protonyms_with_non_fossil_taxa.rb, app/database_scripts/database_scripts/history_items_with_unbalanced_parentheses_braces_or_brackets.rb, app/database_scripts/database_scripts/non_fossil_protonyms_with_fossil_taxa.rb, app/database_scripts/database_scripts/obsolete_combinations_with_protonyms_not_matching_its_current_taxons_protonym.rb, app/database_scripts/database_scripts/protonym_references_without_pdfs.rb, app/database_scripts/database_scripts/protonyms_with_more_than_one_species_in_the_same_genus.rb, app/database_scripts/database_scripts/protonyms_with_more_than_one_taxon_with_associated_history_items.rb, app/database_scripts/database_scripts/protonyms_with_more_than_one_terminal_taxon.rb, app/database_scripts/database_scripts/protonyms_with_more_than_one_valid_taxon.rb, app/database_scripts/database_scripts/protonyms_with_notes_taxt.rb, app/database_scripts/database_scripts/protonyms_with_taxa_with_incompatible_statuses.rb, app/database_scripts/database_scripts/protonyms_with_type_notes_taxt.rb, app/database_scripts/database_scripts/reference_documents_with_weird_actual_urls.rb, app/database_scripts/database_scripts/references_with_author_names_suffixes.rb, app/database_scripts/database_scripts/references_with_blank_pdf_urls_and_filenames.rb, app/database_scripts/database_scripts/references_with_less_parsable_pagination.rb, app/database_scripts/database_scripts/references_with_pdfs_not_hosted_by_us.rb, app/database_scripts/database_scripts/references_without_pdfs.rb, app/database_scripts/database_scripts/series_volume_issue_investigation.rb, app/database_scripts/database_scripts/species_group_protonyms_without_biogeographic_regions.rb, app/database_scripts/database_scripts/taxa_with_disagreeing_name_parts.rb, app/database_scripts/database_scripts/valid_taxa_with_non_valid_parents.rb, app/decorators/database_script_decorator.rb, app/models/database_scripts/empty_status.rb, app/models/soft_validations.rb, app/views/database_scripts/index.haml
Improve empty-checks for the "Show empty" button by filtering out more false positives and highlighting regression-tests that are not empty.
=> Improve empty-checks for database scripts

app/forms/reference_form.rb, app/models/author_name.rb, app/models/reference.rb, app/models/reference_author_name.rb, app/observers/reference_document_observer.rb, spec/factories/references.rb, spec/forms/reference_form_spec.rb, spec/models/reference_author_name_spec.rb, spec/models/reference_spec.rb, spec/observers/reference_observer_spec.rb
Easier to work with since `after_add` and `after_remove` trigger saves for new reference records, which has causes issues for a long time.
=> Create fewer PaperTrail versions by explicitly updating reference caches

app/controllers/editors_panels/restart_and_reindex_solrs_controller.rb, app/services/restart_and_reindex_solr.rb, app/views/editors_panels/index.haml, config/routes.rb, spec/controllers/editors_panels/restart_and_reindex_solrs_controller_spec.rb
Add button to the Editor's Panel for restarting and reindexing Solr (superadmins only).
Very "hmm", but OK as long as we're only running a single server app server instance.
=> Add button for restarting and reindexing Solr

docker/antcat-database.docker
Docker can cache the result of `bundle install` for subsequent builds. By adding it to the docker image, the gems don't need to be downloaded and installed for every run.
Splitting up the run commands allows less of the build cache to be invalidated when the codebase changes.
=> Add bundle install command to dockerfile

app/assets/stylesheets/foundation_and_overrides.sass
Fix for issue introduced in https://github.com/calacademy-research/antcat/pull/1265
=> Fix to make hidden `abbr` underlines visible

app/decorators/database_script_decorator.rb, app/models/database_script.rb, app/models/database_scripts/end_data_attributes.rb, app/views/database_scripts/index.haml, app/views/database_scripts/show.haml, features/editors_panel/database_scripts.feature, lib/generators/templates/database_script.rb.erb, spec/decorators/database_script_decorator_spec.rb, spec/models/database_scripts/end_data_attributes_spec.rb, spec/services/markdowns/parse_antcat_tags_spec.rb
For https://github.com/calacademy-research/antcat-issues/issues/113
=> Unify database script taggings (`tags` vs. `section` vs. `category`)

app/controllers/api/v1/reference_documents_controller.rb, app/controllers/references/downloads_controller.rb, app/exporters/exporters/endnote/formatter.rb, app/models/reference.rb, app/models/reference_document.rb, app/views/references/_form.haml, features/reference_form/edit_reference_successfully.feature, features/step_definitions/reference_steps.rb, public/api/v1/swagger.yaml, spec/controllers/api/v1/reference_documents_controller_spec.rb, spec/controllers/references/downloads_controller_spec.rb, spec/decorators/reference_decorator_spec.rb, spec/factories/reference_documents.rb, spec/forms/reference_form_spec.rb, spec/injectable_formatters/antweb_formatter/reference_link_spec.rb, spec/models/reference_document_spec.rb, spec/models/reference_spec.rb
For https://github.com/calacademy-research/antcat-issues/issues/114
=> Don't allow creating new `ReferenceDocument`s with `url`s

app/models/grouped_history_item.rb, app/models/history/definition.rb, app/models/history/definitions.rb, app/models/history_item.rb, app/models/taxon.rb, app/presenters/history_presenter.rb, app/views/catalog/_show/_taxon_description.haml, spec/models/history/definitions_spec.rb, spec/models/history_item_spec.rb, spec/presenters/history_presenter_spec.rb
=> Add support for mirrored history items, and enable for `JuniorSynonymOf` items

app/database_scripts/database_scripts/taxa_with_disagreeing_taxon_relations.rb, app/database_scripts/database_scripts/valid_taxa_with_non_valid_parents.rb, app/models/taxon.rb, app/models/taxon_sti_subclasses/family.rb, app/models/taxon_sti_subclasses/genus_group_taxon.rb, app/models/taxon_sti_subclasses/genus_group_taxon_sti_subclasses/genus.rb, app/models/taxon_sti_subclasses/genus_group_taxon_sti_subclasses/subgenus.rb, app/models/taxon_sti_subclasses/species_group_taxon.rb, app/models/taxon_sti_subclasses/species_group_taxon_sti_subclasses/infrasubspecies.rb, app/models/taxon_sti_subclasses/species_group_taxon_sti_subclasses/species.rb, app/models/taxon_sti_subclasses/species_group_taxon_sti_subclasses/subspecies.rb, app/models/taxon_sti_subclasses/subfamily.rb, app/models/taxon_sti_subclasses/subtribe.rb, app/models/taxon_sti_subclasses/tribe.rb, spec/exporters/exporters/antweb/taxonomic_attributes_spec.rb, spec/factories/taxa.rb, spec/models/taxon_sti_subclasses/family_spec.rb, spec/models/taxon_sti_subclasses/genus_group_taxon_sti_subclasses/genus_spec.rb, spec/models/taxon_sti_subclasses/genus_group_taxon_sti_subclasses/subgenus_spec.rb, spec/models/taxon_sti_subclasses/species_group_taxon_sti_subclasses/infrasubspecies_spec.rb, spec/models/taxon_sti_subclasses/species_group_taxon_sti_subclasses/species_spec.rb, spec/models/taxon_sti_subclasses/species_group_taxon_sti_subclasses/subspecies_spec.rb, spec/models/taxon_sti_subclasses/subfamily_spec.rb, spec/models/taxon_sti_subclasses/subtribe_spec.rb, spec/models/taxon_sti_subclasses/tribe_spec.rb
For https://github.com/calacademy-research/antcat-issues/issues/125
* Ensure irrelevant columns are not set
* Don't store `subfamily_id` of subtribes (inferrable from tribe)
* Don't store `tribe_id` of subgenera (inferrable from genus)
* Don't store `subgenus_id` of subspecies and infraspecies (inferrable from genus)
=> Start deduping inferrable taxon relations (subtribes/subgenera/subspecies/infraspecies)

docker/docker-compose.yml
```
db_1      | [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
db_1      |     Remove MYSQL_USER="root" and use one of the following to control the root user password:
db_1      |     - MYSQL_ROOT_PASSWORD
db_1      |     - MYSQL_ALLOW_EMPTY_PASSWORD
db_1      |     - MYSQL_RANDOM_ROOT_PASSWORD
docker_db_1 exited with code 1
```
=> AntWeb export: update mysql config

Gemfile, Gemfile.lock, spec/models/reference_document_spec.rb
Missed in #1383
`webrick` is not a default gem in Ruby 3: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
=> Add missing gem `webrick`

Gemfile, Gemfile.lock
See https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-the-packaged-libraries
```
+ 1m 29s       ERROR: It looks like you're trying to use Nokogiri as a precompiled native gem on a system
+ 1m 29s              with an unsupported version of glibc.
+ 1m 29s
+ 1m 29s         /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /data/antcat/shared/bundled_gems/ruby/3.2.0/gems/nokogiri-1.18.4-x86_64-linux-gnu/lib/nokogiri/3.2/nokogiri.so) - /data/antcat/shared/bundled_gems/ruby/3.2.0/gems/nokogiri-1.18.4-x86_64-linux-gnu/lib/nokogiri/3.2/nokogiri.so
+ 1m 29s
+ 1m 29s         If that's the case, then please install Nokogiri via the `ruby` platform gem:
+ 1m 29s             gem install nokogiri --platform=ruby
+ 1m 29s         or:
+ 1m 29s …
```
=> gems: fix nokogiri platforms
